export type AdvanceSeed = {
  internalName: string
  ingredients: string[]
  source: string
  target: string
}

export function getAdvanceDefinitions(): AdvanceSeed[] {
  return [
    {
      internalName: 'Avance a Light Supplicant',
      ingredients: ['rezar', 'luz'],
      source: 'bard',
      target: 'light-supplicant',
    },
    {
      internalName: 'Avance a Solar High Priest',
      ingredients: ['fuego', 'bendicion'],
      source: 'light-supplicant',
      target: 'solar-high-priest',
    },
    {
      internalName: 'Avance a Notario',
      ingredients: ['contrato', 'divinidad'],
      source: 'solar-high-priest',
      target: 'notary',
    },
    {
      internalName: 'Avance a Priest of Light',
      ingredients: ['purificacion', 'oficiante'],
      source: 'notary',
      target: 'priest-of-light',
    },
    {
      internalName: 'Avance a Unshadowed',
      ingredients: ['purificacion', 'divinidad'],
      source: 'priest-of-light',
      target: 'unshadowed',
    },
    {
      internalName: 'Avance a Justice Mentor',
      ingredients: ['justicia', 'orden'],
      source: 'unshadowed',
      target: 'justice-mentor',
    },
    {
      internalName: 'Avance a Lightseeker',
      ingredients: ['autoridad-solar', 'luz'],
      source: 'justice-mentor',
      target: 'lightseeker',
    },
    {
      internalName: 'Avance a Sheriff',
      ingredients: ['jurisdiccion', 'percepcion'],
      source: 'arbitro',
      target: 'sheriff',
    },
    {
      internalName: 'Avance a Interrogator',
      ingredients: ['dolor', 'psique'],
      source: 'sheriff',
      target: 'interrogator',
    },
    {
      internalName: 'Avance a Judge',
      ingredients: ['ley', 'autoridad'],
      source: 'interrogator',
      target: 'judge',
    },
    {
      internalName: 'Avance a Disciplinary Paladin',
      ingredients: ['caballero', 'castigo'],
      source: 'judge',
      target: 'disciplinary-paladin',
    },
    {
      internalName: 'Avance a Imperative Mage',
      ingredients: ['lenguaje', 'autoridad'],
      source: 'disciplinary-paladin',
      target: 'imperative-mage',
    },
    {
      internalName: 'Avance a Chaos Hunter',
      ingredients: ['caza', 'desorden'],
      source: 'imperative-mage',
      target: 'chaos-hunter',
    },
    {
      internalName: 'Avance a Balancer',
      ingredients: ['equilibrio', 'autoridad'],
      source: 'chaos-hunter',
      target: 'balancer',
    },
    {
      internalName: 'Avance a Midnight Poet',
      ingredients: ['poesia', 'noche'],
      source: 'sleepless',
      target: 'midnight-poet',
    },
    {
      internalName: 'Avance a Nightmare',
      ingredients: ['pesadilla', 'psique'],
      source: 'midnight-poet',
      target: 'nightmare',
    },
    {
      internalName: 'Avance a Soul Assurer',
      ingredients: ['requiem', 'alma'],
      source: 'nightmare',
      target: 'soul-assurer',
    },
    {
      internalName: 'Avance a Spirit Warlock',
      ingredients: ['espiritu', 'sello'],
      source: 'soul-assurer',
      target: 'spirit-warlock',
    },
    {
      internalName: 'Avance a Nightwatcher',
      ingredients: ['noche', 'dominio'],
      source: 'spirit-warlock',
      target: 'nightwatcher',
    },
    {
      internalName: 'Avance a Horror Bishop',
      ingredients: ['horror', 'dominio'],
      source: 'nightwatcher',
      target: 'horror-bishop',
    },
    {
      internalName: 'Avance a Servant of Concealment',
      ingredients: ['ocultamiento', 'secreto'],
      source: 'horror-bishop',
      target: 'servant-of-concealment',
    },
    {
      internalName: 'Avance a Gravedigger',
      ingredients: ['espiritu', 'percepcion-espiritual'],
      source: 'corpse-collector',
      target: 'gravedigger',
    },
    {
      internalName: 'Avance a Spirit Medium',
      ingredients: ['canalizacion-espiritual', 'percepcion-espiritual'],
      source: 'gravedigger',
      target: 'spirit-medium',
    },
    {
      internalName: 'Avance a Spirit Guide',
      ingredients: ['lenguaje-de-los-muertos', 'muerto-viviente'],
      source: 'spirit-medium',
      target: 'spirit-guide',
    },
    {
      internalName: 'Avance a Gatekeeper',
      ingredients: ['sello', 'puerta-al-inframundo'],
      source: 'spirit-guide',
      target: 'gatekeeper',
    },
    {
      internalName: 'Avance a Undying',
      ingredients: ['resurreccion', 'ciclo'],
      source: 'gatekeeper',
      target: 'undying',
    },
    {
      internalName: 'Avance a Ferryman',
      ingredients: ['navegacion', 'rio'],
      source: 'undying',
      target: 'ferryman',
    },
    {
      internalName: 'Avance a Death Consul',
      ingredients: ['autoridad', 'muerte'],
      source: 'ferryman',
      target: 'death-consul',
    },
    {
      internalName: 'Avance a Trickmaster',
      ingredients: ['registro', 'truco'],
      source: 'aprendiz',
      target: 'trickmaster',
    },
    {
      internalName: 'Avance a Escriba',
      ingredients: ['poder-beyonder', 'registro'],
      source: 'astrologo',
      target: 'escriba',
    },
    {
      internalName: 'Avance a Traveler',
      ingredients: ['apertura', 'mundo-espiritual'],
      source: 'escriba',
      target: 'traveler',
    },
    {
      internalName: 'Avance a Secrets Sorcerer',
      ingredients: ['espacio', 'secreto'],
      source: 'traveler',
      target: 'secrets-sorcerer',
    },
    {
      internalName: 'Avance a Wanderer',
      ingredients: ['espacio-exterior', 'mundo-astral'],
      source: 'secrets-sorcerer',
      target: 'wanderer',
    },
    {
      internalName: 'Avance a Planeswalker',
      ingredients: ['mundo', 'proyeccion-astral'],
      source: 'wanderer',
      target: 'planeswalker',
    },
    {
      internalName: 'Avance a Swindler',
      ingredients: ['fortuna', 'truco'],
      source: 'marauder',
      target: 'swindler',
    },
    {
      internalName: 'Avance a Cryptologist',
      ingredients: ['dato', 'misticismo'],
      source: 'swindler',
      target: 'cryptologist',
    },
    {
      internalName: 'Avance a Prometheus',
      ingredients: ['robo', 'poder-beyonder'],
      source: 'cryptologist',
      target: 'prometheus',
    },
    {
      internalName: 'Avance a Folk of Rage',
      ingredients: ['furia', 'mar'],
      source: 'sailor',
      target: 'folk-of-rage',
    },
    {
      internalName: 'Avance a Robot',
      ingredients: ['fuerza', 'adivinacion'],
      source: 'monster',
      target: 'robot',
    },
    {
      internalName: 'Avance a Clown',
      ingredients: ['control-corporal', 'danger-intuition'],
      source: 'seer',
      target: 'clown',
    },
    {
      internalName: 'Avance a Listener',
      ingredients: ['escucha', 'locura'],
      source: 'secret-suplicant',
      target: 'listener',
    },
    {
      internalName: 'Avance a Mago',
      ingredients: ['ilusion', 'magia'],
      source: 'clown',
      target: 'mago',
    },
    {
      internalName: 'Avance a Astrólogo',
      ingredients: ['adivinacion', 'cuerpo-celeste'],
      source: 'trickmaster',
      target: 'astrologo',
    },
    {
      internalName: 'Avance a Dream Stealer',
      ingredients: ['blasfemia', 'secreto'],
      source: 'prometheus',
      target: 'dream-stealer',
    },
    {
      internalName: 'Avance a Parasite',
      ingredients: ['avatar', 'parasitismo'],
      source: 'dream-stealer',
      target: 'parasite',
    },
    {
      internalName: 'Avance a Mentor of Deceit',
      ingredients: ['engano', 'distorsion'],
      source: 'parasite',
      target: 'mentor-of-deceit',
    },
    {
      internalName: 'Avance a Trojan Horse of Destiny',
      ingredients: ['suplantacion', 'destino'],
      source: 'mentor-of-deceit',
      target: 'trojan-horse-of-destiny',
    },
    {
      internalName: 'Avance a Lucky One',
      ingredients: ['suerte', 'cambio-cualitativo'],
      source: 'robot',
      target: 'lucky-one',
    },
    {
      internalName: 'Avance a Shadow Ascetic',
      ingredients: ['ocultamiento', 'sombra'],
      source: 'listener',
      target: 'shadow-ascetic',
    },
    {
      internalName: 'Avance a Calamity Priest',
      ingredients: ['danger-intuition', 'calamidad'],
      source: 'lucky-one',
      target: 'calamity-priest',
    },
    {
      internalName: 'Avance a Faceless',
      ingredients: ['disfraz', 'control-corporal'],
      source: 'mago',
      target: 'faceless',
    },
    {
      internalName: 'Avance a Rose Bishop',
      ingredients: ['carne-y-sangre', 'magia'],
      source: 'shadow-ascetic',
      target: 'rose-bishop',
    },
    {
      internalName: 'Avance a Shepherd',
      ingredients: ['devoracion', 'alma'],
      source: 'rose-bishop',
      target: 'shepherd',
    },
    {
      internalName: 'Avance a Marionetista',
      ingredients: ['hilos-del-cuerpo-espiritual', 'marioneta'],
      source: 'faceless',
      target: 'marionetista',
    },
    {
      internalName: 'Avance a Winner',
      ingredients: ['suerte', 'fortuna'],
      source: 'calamity-priest',
      target: 'winner',
    },
    {
      internalName: 'Avance a Bizarro Sorcerer',
      ingredients: ['otorgamiento', 'marioneta'],
      source: 'marionetista',
      target: 'bizarro-sorcerer',
    },
    {
      internalName: 'Avance a Black Knight',
      ingredients: ['degeneracion', 'caballero'],
      source: 'shepherd',
      target: 'black-knight',
    },
    {
      internalName: 'Avance a Misfortune Mage',
      ingredients: ['bendicion', 'mala-suerte'],
      source: 'winner',
      target: 'misfortune-mage',
    },
    {
      internalName: 'Avance a Scholar of Yore',
      ingredients: ['proyeccion', 'historia'],
      source: 'bizarro-sorcerer',
      target: 'scholar-of-yore',
    },
    {
      internalName: 'Avance a Invocador de Milagros',
      ingredients: ['invocador', 'milagro'],
      source: 'scholar-of-yore',
      target: 'miracle-invoker',
    },
    {
      internalName: 'Avance a Chaoswalker',
      ingredients: ['desorden', 'destino'],
      source: 'misfortune-mage',
      target: 'chaoswalker',
    },
    {
      internalName: 'Avance a Soothsayer',
      ingredients: ['profecia', 'mundo-espiritual'],
      source: 'chaoswalker',
      target: 'soothsayer',
    },
    {
      internalName: 'Avance a Trinity Templar',
      ingredients: ['trinidad', 'carne-y-sangre'],
      source: 'black-knight',
      target: 'trinity-templar',
    },
    {
      internalName: 'Avance a Profane Presbyter',
      ingredients: ['lenguaje', 'profanacion'],
      source: 'trinity-templar',
      target: 'profane-presbyter',
    },
    {
      internalName: 'Avance a Telepathist',
      ingredients: ['pensamiento', 'percepcion'],
      source: 'spectator',
      target: 'telepathist',
    },
    {
      internalName: 'Avance a Psychiatrist',
      ingredients: ['psique', 'intervencion'],
      source: 'telepathist',
      target: 'psychiatrist',
    },
    {
      internalName: 'Avance a Hypnotist',
      ingredients: ['sugestion', 'subconsciente'],
      source: 'psychiatrist',
      target: 'hypnotist',
    },
    {
      internalName: 'Avance a Dreamwalker',
      ingredients: ['sueno', 'proyeccion-astral'],
      source: 'hypnotist',
      target: 'dreamwalker',
    },
    {
      internalName: 'Avance a Manipulator',
      ingredients: ['dominacion', 'mar-del-subconsciente-colectivo'],
      source: 'dreamwalker',
      target: 'manipulator',
    },
    {
      internalName: 'Avance a Dream Weaver',
      ingredients: ['sueno', 'imaginacion'],
      source: 'manipulator',
      target: 'dream-weaver',
    },
    {
      internalName: 'Avance a Discerner',
      ingredients: ['discernimiento', 'psique'],
      source: 'dream-weaver',
      target: 'discerner',
    },
    {
      internalName: 'Avance a Seafarer',
      ingredients: ['navegacion', 'magia-acuatica'],
      source: 'folk-of-rage',
      target: 'seafarer',
    },
    {
      internalName: 'Avance a Wind-blessed',
      ingredients: ['viento', 'bendicion'],
      source: 'seafarer',
      target: 'wind-blessed',
    },
    {
      internalName: 'Avance a Ocean Songster',
      ingredients: ['canto', 'relampago'],
      source: 'wind-blessed',
      target: 'ocean-songster',
    },
    {
      internalName: 'Avance a Cataclysmic Interrer',
      ingredients: ['oficiante', 'calamidad'],
      source: 'ocean-songster',
      target: 'cataclysmic-interrer',
    },
    {
      internalName: 'Avance a Sea King',
      ingredients: ['rey', 'mar'],
      source: 'cataclysmic-interrer',
      target: 'sea-king',
    },
    {
      internalName: 'Avance a Calamidad',
      ingredients: ['calamidad', 'tormenta'],
      source: 'sea-king',
      target: 'calamity',
    },
  ]
}
