export type ElementSeed = {
  slug: string
  name: string
  description: string
  iconKey: string
  type: string
  tier: number
  isStarter?: boolean
  isHiddenUntilDiscovered?: boolean
  isMajorDiscovery?: boolean
  revealTitle?: string
  revealText?: string
  unlockedByType?: string
  unlockedBySequenceNumber?: number
  // Desbloqueo espontáneo por cantidad: se satisface cuando el jugador tiene
  // al menos esta cantidad de elementos activos descubiertos (>=).
  unlockedAtDiscoveryCount?: number
  isActive?: boolean
  categoryId: string
}

export type ElementCategoryIds = {
  mundano: string
  conceptos: string
  misticismo: string
  beyonder: string
}

export function getElementDefinitions({
  mundano,
  conceptos,
  misticismo,
  beyonder,
}: ElementCategoryIds): ElementSeed[] {
  return [
    {
      slug: 'ojo',
      name: 'Ojo',
      description: 'Un órgano humilde que, sin embargo, lo observa todo.',
      iconKey: 'eye',
      type: 'MUNDANO',
      tier: 0,
      isStarter: true,
      isHiddenUntilDiscovered: false,
      categoryId: mundano,
    },
    {
      slug: 'moneda',
      name: 'Moneda',
      description: 'Metal acuñado. Cara o cruz: alguien siempre pierde.',
      iconKey: 'coins',
      type: 'MUNDANO',
      tier: 0,
      isStarter: true,
      isHiddenUntilDiscovered: false,
      categoryId: mundano,
    },
    {
      slug: 'humano',
      name: 'Humano',
      description: 'Frágil, curioso y convencido de que el mundo le pertenece.',
      iconKey: 'user-round',
      type: 'MUNDANO',
      tier: 0,
      isStarter: true,
      isHiddenUntilDiscovered: false,
      categoryId: mundano,
    },
    {
      slug: 'apuesta',
      name: 'Apuesta',
      description: 'Un humano y una moneda: el pacto más antiguo con el azar.',
      iconKey: 'dices',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'vision',
      name: 'Visión',
      description: 'Cuando dos miradas coinciden, algo más que luz se enfoca.',
      iconKey: 'scan-eye',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    // ----- Cadena del Ocultamiento -----
    // Estos slugs coinciden con los elementos ya usados en la base actual.
    {
      slug: 'experiencia-2',
      name: 'Experiencia',
      description: 'Lo vivido deja lecciones que ningún libro puede sustituir.',
      iconKey: 'history',
      type: 'CONCEPTO',
      tier: 0,
      categoryId: conceptos,
    },
    {
      slug: 'conocimiento',
      name: 'Conocimiento',
      description: 'Comprensión acumulada y ordenada por la razón.',
      iconKey: 'brain',
      type: 'CONCEPTO',
      tier: 0,
      categoryId: conceptos,
    },
    {
      slug: 'informacion',
      name: 'Información',
      description: 'El conocimiento interpreta el dato y le da significado.',
      iconKey: 'file-text',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'prudencia',
      name: 'Prudencia',
      description:
        'La experiencia y el conocimiento permiten reconocer qué conviene no revelar.',
      iconKey: 'shield',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'reserva',
      name: 'Reserva',
      description: 'La información manejada con prudencia se mantiene restringida.',
      iconKey: 'lock-keyhole',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'ocultamiento',
      name: 'Ocultamiento',
      description:
        'La reserva aplicada a aquello que puede verse o descubrirse produce ocultamiento.',
      iconKey: 'eye-off',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    // ----- Cadenas de esfuerzo, peligro y control -----
    {
      slug: 'tiempo',
      name: 'Tiempo',
      description: 'La medida invisible que transforma toda acción.',
      iconKey: 'alarm-clock',
      type: 'CONCEPTO',
      tier: 4,
      isStarter: false,
      isHiddenUntilDiscovered: true,
      isMajorDiscovery: true,
      isActive: false,
      revealTitle: 'El Archivo percibe el cambio',
      revealText:
        'Nada permanece inmóvil. Incluso los conceptos dejan una huella al atravesar el tiempo.',
      // Contenido prohibido: no puede descubrirse ni usarse en combinaciones.
      categoryId: conceptos,
    },
    {
      slug: 'trabajo',
      name: 'Trabajo',
      description: 'La voluntad humana aplicada a una necesidad material.',
      iconKey: 'briefcase-business',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'esfuerzo',
      name: 'Esfuerzo',
      description: 'Trabajo sostenido a través del tiempo.',
      iconKey: 'footprints',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'fuerza',
      name: 'Fuerza',
      description: 'El esfuerzo humano convertido en capacidad física.',
      iconKey: 'dumbbell',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'muerte',
      name: 'Muerte',
      description: 'El límite que vuelve urgente toda percepción.',
      iconKey: 'skull',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'intuicion',
      name: 'Intuición',
      description: 'Una certeza que llega antes que la explicación.',
      iconKey: 'lightbulb',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'peligro',
      name: 'Peligro',
      description: 'La muerte percibida antes de que llegue.',
      iconKey: 'triangle-alert',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'danger-intuition',
      name: 'Danger Intuition',
      description: 'La intuición afinada por la presencia constante del peligro.',
      iconKey: 'radar',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'control-corporal',
      name: 'Control corporal',
      description: 'La fuerza guiada por la experiencia del propio cuerpo.',
      iconKey: 'biceps-flexed',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'existencia-oculta',
      name: 'Existencia oculta',
      description: 'Una presencia peligrosa que permanece fuera de la vista.',
      iconKey: 'eye-off',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'revelacion-prohibida',
      name: 'Revelación prohibida',
      description: 'Una verdad que el misticismo mantuvo oculta por una razón.',
      iconKey: 'book-key',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'locura',
      name: 'Locura',
      description: 'La mente humana quebrada por aquello que no debía conocer.',
      iconKey: 'circle-help',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'robot',
      name: 'Robot',
      description: 'Secuencia 8 del Camino del Monstruo.',
      iconKey: 'bot',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'El azar aprende a obedecer',
      revealText: 'Tu cuerpo responde con una precisión que ya no parece humana.',
      categoryId: beyonder,
    },
    {
      slug: 'clown',
      name: 'Clown',
      description: 'Secuencia 8 del Camino del Vidente.',
      iconKey: 'drama',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'Una sonrisa cubre el abismo',
      revealText: 'Dominas el cuerpo mientras ocultas el temblor de la mente.',
      categoryId: beyonder,
    },
    // ----- Escucha, magia, incertidumbre y suerte -----
    {
      slug: 'escucha',
      name: 'Escucha',
      description: 'La percepción humana dirigida hacia lo que otros no oyen.',
      iconKey: 'ear',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'magia',
      name: 'Magia',
      description: 'El conocimiento aplicado sobre las reglas ocultas del misticismo.',
      iconKey: 'wand',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'ilusion',
      name: 'Ilusión',
      description: 'Magia que altera aquello que la percepción acepta como real.',
      iconKey: 'blend',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'incertidumbre',
      name: 'Incertidumbre',
      description: 'Información oculta que impide distinguir certeza de posibilidad.',
      iconKey: 'circle-help',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'suerte',
      name: 'Suerte',
      description: 'El destino inclinándose dentro de un mar de incertidumbre.',
      iconKey: 'clover',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'listener',
      name: 'Listener',
      description: 'Secuencia 8 del Camino del Suplicante de Secretos.',
      iconKey: 'ear',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'Las voces encuentran un oído',
      revealText: 'Ahora escuchas aquello que nunca fue pronunciado.',
      categoryId: beyonder,
    },
    {
      slug: 'mago',
      name: 'Mago',
      description: 'Secuencia 7 del Camino del Vidente.',
      iconKey: 'wand-sparkles',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      revealTitle: 'La realidad acepta el truco',
      revealText: 'La ilusión deja de ser engaño y comienza a obedecerte.',
      categoryId: beyonder,
    },
    // ----- Cambio cualitativo, sombras y carne -----
    {
      slug: 'avance',
      name: 'Avance',
      description: 'El paso de un ser más allá de su estado anterior.',
      iconKey: 'move-up-right',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'cambio-cualitativo',
      name: 'Cambio cualitativo',
      description: 'Una transformación que altera la naturaleza y no solo la cantidad.',
      iconKey: 'blend',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'secuencia-media',
      name: 'Secuencia media',
      description: 'El umbral donde una secuencia deja atrás los primeros pasos del camino.',
      iconKey: 'layers',
      type: 'CONCEPTO',
      tier: 4,
      unlockedBySequenceNumber: 7,
      categoryId: conceptos,
    },
    {
      slug: 'divinidad',
      name: 'Divinidad',
      description: 'Una cualidad que comienza a apartarse de lo enteramente humano.',
      iconKey: 'sun',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'saint',
      name: 'Saint',
      description: 'Un título para quien ha cruzado un límite cualitativo del camino.',
      iconKey: 'award',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'demigod',
      name: 'Demigod',
      description: 'Una existencia situada entre lo mortal y lo divino.',
      iconKey: 'star',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'angel',
      name: 'Ángel',
      description: 'Una existencia divina que ha dejado muy atrás los límites de un semidiós.',
      iconKey: 'star',
      type: 'MISTICISMO',
      tier: 6,
      unlockedBySequenceNumber: 2,
      categoryId: misticismo,
    },
    {
      slug: 'claridad',
      name: 'Claridad',
      description: 'El conocimiento ordena la percepción hasta disipar la confusión.',
      iconKey: 'lightbulb',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'luz',
      name: 'Luz',
      description: 'La claridad atravesando las reglas del misticismo.',
      iconKey: 'sun',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'fuego',
      name: 'Fuego',
      description: 'La luz convertida por la fuerza en calor capaz de transformar la materia.',
      iconKey: 'flame',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'bard',
      name: 'Bard',
      description: 'Secuencia 9 del Camino del Sol. Su canto porta luz y despierta el valor de quienes lo escuchan.',
      iconKey: 'music',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'El canto porta luz',
      revealText: 'Tu voz despierta el valor de quienes reciben su claridad.',
      categoryId: beyonder,
    },
    {
      slug: 'light-supplicant',
      name: 'Light Supplicant',
      description: 'Secuencia 8 del Camino del Sol. Convierte la plegaria en una súplica dirigida hacia la luz.',
      iconKey: 'sun',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      revealTitle: 'La luz escucha tu plegaria',
      revealText: 'Tu voz encuentra respuesta en una claridad que ya no parece distante.',
      categoryId: beyonder,
    },
    {
      slug: 'solar-high-priest',
      name: 'Solar High Priest',
      description: 'Secuencia 7 del Camino del Sol. Oficia con fuego bendecido bajo la autoridad solar.',
      iconKey: 'sun',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      revealTitle: 'El fuego bendecido arde',
      revealText: 'La llama responde a tu oficio bajo la autoridad del sol.',
      categoryId: beyonder,
    },
    {
      slug: 'notary',
      name: 'Notario',
      description: 'Secuencia 6 del Camino del Sol. Sus contratos adquieren el peso de un mandato divino.',
      iconKey: 'scroll-text',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      revealTitle: 'La palabra se convierte en ley',
      revealText: 'Todo juramento pronunciado ante ti comienza a exigir obediencia.',
      categoryId: beyonder,
    },
    {
      slug: 'purificacion',
      name: 'Purificación',
      description: 'Una bendición que expulsa la corrupción y devuelve claridad a lo contaminado.',
      iconKey: 'sparkles',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'priest-of-light',
      name: 'Priest of Light',
      description: 'Secuencia 5 del Camino del Sol. Conduce la purificación mediante la autoridad de la luz.',
      iconKey: 'sun',
      type: 'BEYONDER',
      tier: 8,
      isMajorDiscovery: true,
      revealTitle: 'La luz expulsa toda corrupción',
      revealText: 'La oscuridad retrocede ante una pureza que ahora puedes oficiar.',
      categoryId: beyonder,
    },
    {
      slug: 'hielo',
      name: 'Hielo',
      description: 'Agua inmovilizada por una fuerza que le arrebata el movimiento.',
      iconKey: 'droplets',
      type: 'MUNDANO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'hielo-eterno',
      name: 'Hielo eterno',
      description: 'Hielo sostenido por una continuidad que no permite el deshielo.',
      iconKey: 'star',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'oscuridad',
      name: 'Oscuridad',
      description: 'Una sombra protegida por el ocultamiento hasta excluir toda luz.',
      iconKey: 'moon',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'unshadowed',
      name: 'Unshadowed',
      description: 'Secuencia 4 del Camino del Sol. Su divinidad purificada no admite sombra alguna.',
      iconKey: 'sun',
      type: 'BEYONDER',
      tier: 9,
      isMajorDiscovery: true,
      revealTitle: 'Ninguna sombra permanece',
      revealText: 'La luz te atraviesa sin encontrar oscuridad donde detenerse.',
      categoryId: beyonder,
    },
    {
      slug: 'ave',
      name: 'Ave',
      description: 'Un ave atraída por la luz sin sombras de una existencia purificada.',
      iconKey: 'feather',
      type: 'CRIATURA',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'justicia',
      name: 'Justicia',
      description: 'La ley guiada por el discernimiento para distinguir lo correcto de lo conveniente.',
      iconKey: 'shield',
      type: 'CONCEPTO',
      tier: 5,
      categoryId: conceptos,
    },
    {
      slug: 'codigos',
      name: 'Códigos',
      description: 'La justicia fijada en contratos hasta formar un cuerpo ordenado de normas.',
      iconKey: 'scroll-text',
      type: 'CONCEPTO',
      tier: 6,
      categoryId: conceptos,
    },
    {
      slug: 'justice-mentor',
      name: 'Justice Mentor',
      description: 'Secuencia 3 del Camino del Sol. Enseña una justicia respaldada por autoridad divina.',
      iconKey: 'shield',
      type: 'BEYONDER',
      tier: 10,
      isMajorDiscovery: true,
      revealTitle: 'La justicia encuentra una voz',
      revealText: 'La ley y el orden se convierten en principios que puedes imponer y enseñar.',
      categoryId: beyonder,
    },
    {
      slug: 'artefacto',
      name: 'Artefacto',
      description: 'Una construcción transformada por el misticismo hasta adquirir propiedades imposibles.',
      iconKey: 'gem',
      type: 'OBJETO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'autoridad-solar',
      name: 'Autoridad solar',
      description: 'La divinidad expresada mediante la luz como una autoridad capaz de disipar toda sombra.',
      iconKey: 'sun',
      type: 'MISTICISMO',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'reliquia-solar',
      name: 'Reliquia solar',
      description: 'Un artefacto consagrado por la autoridad solar y saturado de luz divina.',
      iconKey: 'award',
      type: 'OBJETO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'memoria',
      name: 'Memoria',
      description: 'La experiencia preservada en un registro para resistir el paso del tiempo.',
      iconKey: 'history',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'lightseeker',
      name: 'Lightseeker',
      description: 'Secuencia 2 del Camino del Sol. Persigue la luz primordial allí donde la oscuridad intenta ocultarla.',
      iconKey: 'sun',
      type: 'BEYONDER',
      tier: 11,
      isMajorDiscovery: true,
      revealTitle: 'La luz primordial marca el camino',
      revealText: 'Toda oscuridad se convierte en una dirección hacia una luz todavía más pura.',
      categoryId: beyonder,
    },
    {
      slug: 'silueta',
      name: 'Silueta',
      description: 'Una forma visible cuyo interior permanece oculto.',
      iconKey: 'user-round',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'sombra',
      name: 'Sombra',
      description: 'La silueta que la luz proyecta sobre lo desconocido.',
      iconKey: 'moon',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'calamidad',
      name: 'Calamidad mística',
      description: 'Un peligro transformado en desastre de gran escala.',
      iconKey: 'triangle-alert',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'disfraz',
      name: 'Disfraz',
      description: 'La apariencia humana usada para ocultar la identidad.',
      iconKey: 'drama',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'carne',
      name: 'Carne',
      description: 'El cuerpo pierde su condición de ser vivo y queda como materia orgánica.',
      iconKey: 'beef',
      type: 'MUNDANO',
      tier: 1,
      categoryId: mundano,
    },
    {
      slug: 'herida',
      name: 'Herida',
      description: 'La fuerza física aplicada sobre la carne produce daño.',
      iconKey: 'bandage',
      type: 'MUNDANO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'sangre',
      name: 'Sangre',
      description: 'La carne herida deja salir la sangre.',
      iconKey: 'droplets',
      type: 'MUNDANO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'carne-y-sangre',
      name: 'Carne y sangre',
      description: 'Materia orgánica reunida con aquello que le daba vida.',
      iconKey: 'beef',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'lucky-one',
      name: 'Lucky One',
      description: 'Secuencia 7 del Camino del Monstruo.',
      iconKey: 'clover',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    {
      slug: 'shadow-ascetic',
      name: 'Shadow Ascetic',
      description: 'Secuencia 7 del Camino del Suplicante de Secretos.',
      iconKey: 'eye-off',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    {
      slug: 'calamity-priest',
      name: 'Calamity Priest',
      description: 'Secuencia 6 del Camino del Monstruo.',
      iconKey: 'triangle-alert',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    {
      slug: 'faceless',
      name: 'Faceless',
      description: 'Secuencia 6 del Camino del Vidente.',
      iconKey: 'drama',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    {
      slug: 'rose-bishop',
      name: 'Rose Bishop',
      description: 'Secuencia 6 del Camino del Suplicante de Secretos.',
      iconKey: 'droplets',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    // ----- Alma, hambre y ritual de Shepherd -----
    {
      slug: 'espiritu',
      name: 'Espíritu',
      description: 'La parte inmaterial que permanece cuando la vida abandona al humano.',
      iconKey: 'ghost',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'alma',
      name: 'Alma',
      description: 'El espíritu moldeado por toda la experiencia de una existencia.',
      iconKey: 'orbit',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'desgaste',
      name: 'Desgaste',
      description: 'El esfuerzo acumulado deteriora lentamente al cuerpo humano.',
      iconKey: 'history',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'edad',
      name: 'Edad',
      description: 'La huella neutral que deja el tiempo sobre un ser humano.',
      iconKey: 'calendar-clock',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'vejez',
      name: 'Vejez',
      description: 'La edad atravesada por el desgaste de una vida.',
      iconKey: 'hourglass',
      type: 'CONCEPTO',
      tier: 5,
      isActive: false,
      categoryId: conceptos,
    },
    {
      slug: 'hambre',
      name: 'Hambre',
      description: 'El desgaste prolongado en el tiempo exige alimento.',
      iconKey: 'beef',
      type: 'MUNDANO',
      tier: 3,
      categoryId: mundano,
    },
    {
      slug: 'devoracion',
      name: 'Devoración',
      description: 'El hambre consumiendo carne sin medida ni control.',
      iconKey: 'skull',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'influencia',
      name: 'Influencia',
      description: 'Información percibida que altera decisiones y voluntades.',
      iconKey: 'waves',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'shepherd',
      name: 'Shepherd',
      description: 'Secuencia 5 del Camino del Suplicante de Secretos.',
      iconKey: 'user-round',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      categoryId: beyonder,
    },
    {
      slug: 'perdida-de-control',
      name: 'Pérdida de control',
      description: 'El avance fracasa y la voluntad deja de gobernar el cuerpo.',
      iconKey: 'circle-help',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'monstruo-descontrol',
      name: 'Monstruo',
      description: 'Una forma nacida de un avance fallido y fuera de control.',
      iconKey: 'ghost',
      type: 'CRIATURA',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'corrupcion-de-alborotador',
      name: 'Corrupción de alborotador',
      description: 'La corrupción que invade el cuerpo tras perturbar un ritual incompleto.',
      iconKey: 'triangle-alert',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'percepcion',
      name: 'Percepción',
      description: 'El arte de notar aquello que preferiría no ser notado.',
      iconKey: 'radar',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'fortuna',
      name: 'Fortuna',
      description: 'La suma de todas las monedas que aún no han caído.',
      iconKey: 'clover',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'adivinacion',
      name: 'Adivinación',
      description: 'Preguntarle al azar con la esperanza de que responda.',
      iconKey: 'dices',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'seer',
      name: 'Seer',
      description:
        'Secuencia 9 del Camino del Vidente. El primer paso más allá del velo.',
      iconKey: 'scan-eye',
      type: 'BEYONDER',
      tier: 3,
      isMajorDiscovery: true,
      revealTitle: 'El velo se ha abierto',
      revealText: 'Has traspasado la frontera de lo mundano.',
      categoryId: beyonder,
    },
    // ----- Cadena del Suplicante de Secretos -----
    {
      slug: 'secreto',
      name: 'Secreto',
      description: 'Información que el ocultamiento mantiene fuera del alcance de otros.',
      iconKey: 'lock-keyhole',
      type: 'MISTICISMO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'secret-suplicant',
      name: 'Secret Suplicant',
      description:
        'Secuencia 9 del Camino del Suplicante de Secretos. Quien pide saber, paga con algo más que monedas.',
      iconKey: 'book-key',
      type: 'BEYONDER',
      tier: 3,
      isMajorDiscovery: true,
      revealTitle: 'Una puerta te ha oído',
      revealText: 'Has formulado la pregunta correcta ante el umbral equivocado.',
      categoryId: beyonder,
    },
    // ----- Cadena del Monstruo -----
    {
      slug: 'destino',
      name: 'Destino',
      description: 'La dirección que la adivinación reconoce en el paso del tiempo.',
      iconKey: 'dices',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'monster',
      name: 'Monster',
      description:
        'Secuencia 9 del Camino del Monstruo. La suerte lo ama tanto que da miedo.',
      iconKey: 'circle-dot-dashed',
      type: 'BEYONDER',
      tier: 3,
      isMajorDiscovery: true,
      revealTitle: 'La rueda ha girado',
      revealText: 'El destino te ha mirado a los ojos y ha sonreído.',
      categoryId: beyonder,
    },
    // Conceptos que ninguna receta fabrica: se desbloquean al descubrir todos
    // los elementos de la progresión del Vidente.
    {
      slug: 'misticismo',
      name: 'Misticismo',
      description: 'Saberes que la razón prefiere no catalogar.',
      iconKey: 'wand-sparkles',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: misticismo,
    },
    {
      slug: 'beyonder',
      name: 'Beyonder',
      description: 'La noción de que alguien puede cruzar la frontera y no regresar.',
      iconKey: 'star',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: beyonder,
    },
    // ----- Cadena del Mar y la Sirena -----
    {
      slug: 'agua',
      name: 'Agua',
      description: 'El elemento que fluye, se adapta y jamás se rompe.',
      iconKey: 'droplets',
      type: 'MUNDANO',
      tier: 0,
      categoryId: mundano,
    },
    {
      slug: 'acumulacion',
      name: 'Acumulación',
      description: 'Lo pequeño repetido sin descanso hasta volverse inmenso.',
      iconKey: 'layers',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'mar',
      name: 'Mar',
      description: 'El agua acumulada hasta perder su orilla.',
      iconKey: 'waves',
      type: 'MUNDANO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'criatura',
      name: 'Criatura',
      description: 'La carne y el alma unidas en una forma que ya no es del todo humana.',
      iconKey: 'ghost',
      type: 'CRIATURA',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'criatura-beyonder',
      name: 'Criatura Beyonder',
      description: 'Una criatura tocada por el poder de quien cruzó la frontera.',
      iconKey: 'skull',
      type: 'CRIATURA',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'ritmo',
      name: 'Ritmo',
      description: 'La escucha que aprende a medirse con el tiempo.',
      iconKey: 'hourglass',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'canto',
      name: 'Canto',
      description: 'El ritmo que un humano convierte en voz.',
      iconKey: 'feather',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'criatura-beyonder-acuatica',
      name: 'Criatura Beyonder Acuática',
      description: 'Una criatura Beyonder que ha hecho del mar su morada.',
      iconKey: 'anchor',
      type: 'CRIATURA',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'sirena',
      name: 'Sirena',
      description: 'La criatura acuática cuyo canto no promete nada bueno.',
      iconKey: 'moon-star',
      type: 'CRIATURA',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'marionetista',
      name: 'Marionetista',
      description:
        'Secuencia 5 del Camino del Vidente. Quien maneja los hilos ya no distingue su propia mano de la ajena.',
      iconKey: 'drama',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      revealTitle: 'Los hilos responden a tu voluntad',
      revealText: 'Faceless deja de fingir un rostro: ahora mueve los de otros.',
      categoryId: beyonder,
    },
    // ----- Cadena del Cuerpo Espiritual y la Marioneta -----
    {
      slug: 'cuerpo-espiritual',
      name: 'Cuerpo Espiritual',
      description: 'El humano despojado de su cuerpo mundano, sostenido apenas por el misticismo.',
      iconKey: 'orbit',
      type: 'MISTICISMO',
      tier: 3,
      categoryId: misticismo,
    },
    {
      slug: 'espiritualidad',
      name: 'Espiritualidad',
      description: 'Lo que el misticismo revela cuando se posa sobre un humano.',
      iconKey: 'sparkles',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'percepcion-espiritual',
      name: 'Percepción espiritual',
      description: 'La percepción afinada para reconocer espíritus y fenómenos del mundo invisible.',
      iconKey: 'radar',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'vision-espiritual',
      name: 'Visión espiritual',
      description: 'La visión transformada por el misticismo hasta percibir lo invisible.',
      iconKey: 'scan-eye',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'continuidad',
      name: 'Continuidad',
      description: 'El tiempo que se repite sin quebrarse.',
      iconKey: 'hourglass',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'proyeccion',
      name: 'Proyección',
      description: 'Una silueta que avanza más allá de su dueño.',
      iconKey: 'telescope',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'extension',
      name: 'Extensión',
      description: 'La proyección sostenida en una continuidad que no termina.',
      iconKey: 'move-up-right',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'hilos-del-cuerpo-espiritual',
      name: 'Hilos del Cuerpo Espiritual',
      description: 'El cuerpo espiritual estirado hasta convertirse en cuerdas invisibles.',
      iconKey: 'gem',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'marioneta',
      name: 'Marioneta',
      description: 'Los hilos del cuerpo espiritual encontrando algo -o alguien- a quien mover.',
      iconKey: 'drama',
      type: 'OBJETO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'desastre',
      name: 'Desastre',
      description: 'La ruina que llega sin avisar y no distingue a quién alcanza.',
      iconKey: 'triangle-alert',
      type: 'MISTICISMO',
      tier: 0,
      categoryId: misticismo,
    },
    {
      slug: 'mala-suerte',
      name: 'Mala Suerte',
      description: 'La suerte vuelta del revés por el desastre.',
      iconKey: 'skull',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'procedimiento',
      name: 'Procedimiento',
      description: 'La información ordenada por el trabajo hasta volverse repetible.',
      iconKey: 'notebook-tabs',
      type: 'CONCEPTO',
      tier: 3,
      categoryId: conceptos,
    },
    {
      slug: 'ritual',
      name: 'Ritual',
      description: 'Un procedimiento que el misticismo vuelve sagrado.',
      iconKey: 'scroll-text',
      type: 'MISTICISMO',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'Nueva disciplina: Ritual',
      revealText:
        'Un avance transforma la naturaleza de una secuencia. Un ritual prepara al Beyonder para sobrevivir a esa transformación.',
      categoryId: misticismo,
    },
    {
      slug: 'rezar',
      name: 'Rezar',
      description: 'El ritual dirigido hacia lo que permanece oculto, con la esperanza de ser oído.',
      iconKey: 'landmark',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'sacrificio',
      name: 'Sacrificio',
      description: 'El ritual que exige algo a cambio de lo oculto.',
      iconKey: 'flame',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'otorgamiento',
      name: 'Otorgamiento',
      description: 'Lo oculto que responde al ritual y concede lo pedido.',
      iconKey: 'key-round',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'winner',
      name: 'Winner',
      description:
        'Secuencia 5 del Camino del Monstruo. La suerte deja de ser un don y se convierte en destino garantizado.',
      iconKey: 'trophy',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      revealTitle: 'Ganar deja de ser cuestión de azar',
      revealText: 'Calamity Priest descubre que el desastre también puede jugar a tu favor.',
      categoryId: beyonder,
    },
    {
      slug: 'bizarro-sorcerer',
      name: 'Bizarro Sorcerer',
      description:
        'Secuencia 4 del Camino del Vidente. Los hilos ya no mueven marionetas: mueven la realidad misma.',
      iconKey: 'flask-conical',
      type: 'BEYONDER',
      tier: 8,
      isMajorDiscovery: true,
      revealTitle: 'La magia deja de pedir permiso',
      revealText: 'Marionetista comprende que también la realidad puede tener hilos.',
      categoryId: beyonder,
    },
    // ----- Cadena de la Corrupción, el Guerrero y la Comunidad -----
    {
      slug: 'corrupcion',
      name: 'Corrupción',
      description: 'La locura que un Beyonder disemina sin proponérselo.',
      iconKey: 'triangle-alert',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'degeneracion',
      name: 'Degeneración',
      description: 'La corrupción que el tiempo no cura, sino que profundiza.',
      iconKey: 'history',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'guerrero',
      name: 'Guerrero',
      description: 'El humano que convierte la fuerza en oficio.',
      iconKey: 'swords',
      type: 'MUNDANO',
      tier: 3,
      categoryId: mundano,
    },
    {
      slug: 'caballero',
      name: 'Caballero',
      description: 'La experiencia que pule al guerrero hasta volverlo disciplina.',
      iconKey: 'medal',
      type: 'MUNDANO',
      tier: 4,
      categoryId: mundano,
    },
    {
      slug: 'familia',
      name: 'Familia',
      description: 'Dos humanos que deciden dejar de estar solos.',
      iconKey: 'user-round',
      type: 'CONCEPTO',
      tier: 1,
      categoryId: conceptos,
    },
    {
      slug: 'familia-angelical',
      name: 'Familia angelical',
      description: 'Un linaje cuya historia y autoridad se sostienen sobre la existencia de un ángel.',
      iconKey: 'award',
      type: 'MISTICISMO',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'familia-augustus',
      name: 'Familia Augustus',
      description: 'Una familia angelical que gobierna mediante la ley, la autoridad y sus interpretaciones.',
      iconKey: 'crown',
      type: 'MISTICISMO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'religion',
      name: 'Religión',
      description: 'Una comunidad organizada alrededor de la divinidad, sus símbolos y sus mandatos.',
      iconKey: 'book-open',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'organizacion-secreta',
      name: 'Organización secreta',
      description: 'Una religión que sirve a una existencia oculta lejos de la mirada pública.',
      iconKey: 'eye-off',
      type: 'MISTICISMO',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'orden-secreta',
      name: 'Orden Secreta',
      description: 'Una organización secreta guiada por videntes que interpretan el destino desde las sombras.',
      iconKey: 'scan-eye',
      type: 'MISTICISMO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'orden-aurora',
      name: 'Orden Aurora',
      description: 'Una organización secreta cuyos suplicantes escuchan revelaciones prohibidas.',
      iconKey: 'sun',
      type: 'MISTICISMO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'iglesia',
      name: 'Iglesia',
      description: 'Una religión asentada en una ciudad hasta convertirse en institución.',
      iconKey: 'landmark',
      type: 'MUNDANO',
      tier: 7,
      categoryId: mundano,
    },
    {
      slug: 'reino-de-loen',
      name: 'Reino de Loen',
      description: 'Una nación gobernada por el linaje angelical de la Familia Augustus.',
      iconKey: 'crown',
      type: 'MUNDANO',
      tier: 9,
      categoryId: mundano,
    },
    {
      slug: 'iglesia-del-senor-de-las-tormentas',
      name: 'Iglesia del Señor de las Tormentas',
      description: 'Una iglesia de Loen consagrada al señor del mar, el viento y el relámpago.',
      iconKey: 'cloud-lightning',
      type: 'MISTICISMO',
      tier: 10,
      categoryId: misticismo,
    },
    {
      slug: 'iglesia-de-la-noche-eterna',
      name: 'Iglesia de la Noche Eterna',
      description: 'Una iglesia de Loen consagrada a la noche, el sueño y el descanso eterno.',
      iconKey: 'moon-star',
      type: 'MISTICISMO',
      tier: 10,
      categoryId: misticismo,
    },
    {
      slug: 'iglesia-del-dios-del-vapor-y-la-maquinaria',
      name: 'Iglesia del Dios del Vapor y la Maquinaria',
      description: 'Una iglesia de Loen consagrada al conocimiento, la industria y las máquinas.',
      iconKey: 'hammer',
      type: 'MISTICISMO',
      tier: 10,
      categoryId: misticismo,
    },
    {
      slug: 'sleepless',
      name: 'Sleepless',
      description: 'Secuencia 9 del Camino del Sleepless. La noche agudiza sus sentidos en lugar de adormecerlos.',
      iconKey: 'moon',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'La noche ya no exige descanso',
      revealText: 'Tus sentidos permanecen despiertos mientras el mundo se entrega al sueño.',
      categoryId: beyonder,
    },
    {
      slug: 'noche',
      name: 'Noche',
      description: 'La oscuridad extendida hasta dominar un periodo completo del tiempo.',
      iconKey: 'moon',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'vigilia',
      name: 'Vigilia',
      description: 'El autocontrol aplicado al sueño para mantener la consciencia despierta.',
      iconKey: 'eye',
      type: 'CONCEPTO',
      tier: 5,
      categoryId: conceptos,
    },
    {
      slug: 'poesia',
      name: 'Poesía',
      description: 'El lenguaje organizado por el ritmo hasta expresar aquello que las palabras solas no alcanzan.',
      iconKey: 'feather',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'requiem',
      name: 'Réquiem',
      description: 'Un canto dedicado a la muerte para guiar y consolar a las almas.',
      iconKey: 'music',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'midnight-poet',
      name: 'Midnight Poet',
      description: 'Secuencia 8 del Camino del Sleepless. Convierte la noche y la poesía en poder espiritual.',
      iconKey: 'feather',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      revealTitle: 'La medianoche encuentra una voz',
      revealText: 'La poesía permite que la noche exprese aquello que mantenía oculto.',
      categoryId: beyonder,
    },
    {
      slug: 'nightmare',
      name: 'Nightmare',
      description: 'Secuencia 7 del Camino del Sleepless. Entra en las pesadillas y gobierna el miedo de la psique.',
      iconKey: 'moon-star',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      revealTitle: 'La pesadilla abre sus puertas',
      revealText: 'El miedo deja de ser una prisión y se convierte en un territorio que puedes recorrer.',
      categoryId: beyonder,
    },
    {
      slug: 'soul-assurer',
      name: 'Soul Assurer',
      description: 'Secuencia 6 del Camino del Sleepless. Calma y asegura las almas mediante réquiems espirituales.',
      iconKey: 'orbit',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      revealTitle: 'El alma encuentra reposo',
      revealText: 'Tu voz puede apaciguar aquello que ni la muerte logró silenciar.',
      categoryId: beyonder,
    },
    {
      slug: 'identidad',
      name: 'Identidad',
      description: 'La diferenciación que permite reconocer a un humano como una existencia única.',
      iconKey: 'scan-eye',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'spirit-warlock',
      name: 'Spirit Warlock',
      description: 'Secuencia 5 del Camino del Sleepless. Sella, invoca y domina espíritus mediante su voluntad.',
      iconKey: 'ghost',
      type: 'BEYONDER',
      tier: 8,
      isMajorDiscovery: true,
      revealTitle: 'Los espíritus responden al sello',
      revealText: 'Tu voluntad adquiere forma suficiente para contener y dirigir lo incorpóreo.',
      categoryId: beyonder,
    },
    {
      slug: 'dominio',
      name: 'Dominio',
      description: 'Una jurisdicción transformada por el misticismo hasta obedecer reglas sobrenaturales.',
      iconKey: 'landmark',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'linaje',
      name: 'Linaje',
      description: 'Un vínculo sostenido por la continuidad a través de generaciones sucesivas.',
      iconKey: 'user-round',
      type: 'CONCEPTO',
      tier: 5,
      categoryId: conceptos,
    },
    {
      slug: 'nightwatcher',
      name: 'Nightwatcher',
      description: 'Secuencia 4 del Camino del Sleepless. Vigila y gobierna un dominio envuelto por la noche.',
      iconKey: 'eye',
      type: 'BEYONDER',
      tier: 9,
      isMajorDiscovery: true,
      revealTitle: 'La noche acepta un vigilante',
      revealText: 'Todo cuanto ocurre en tu dominio nocturno queda expuesto ante tu mirada.',
      categoryId: beyonder,
    },
    {
      slug: 'horror',
      name: 'Horror',
      description: 'Una pesadilla arraigada en la psique hasta convertir el miedo en una presencia real.',
      iconKey: 'ghost',
      type: 'MISTICISMO',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'valor',
      name: 'Valor',
      description: 'El autocontrol que permite actuar incluso ante la certeza del peligro.',
      iconKey: 'shield',
      type: 'CONCEPTO',
      tier: 5,
      categoryId: conceptos,
    },
    {
      slug: 'horror-bishop',
      name: 'Horror Bishop',
      description: 'Secuencia 3 del Camino del Sleepless. Extiende el horror por su dominio hasta gobernar el miedo.',
      iconKey: 'skull',
      type: 'BEYONDER',
      tier: 10,
      isMajorDiscovery: true,
      revealTitle: 'El horror encuentra un dominio',
      revealText: 'La noche convierte cada miedo oculto en una presencia sometida a tu voluntad.',
      categoryId: beyonder,
    },
    {
      slug: 'servant-of-concealment',
      name: 'Servant of Concealment',
      description: 'Secuencia 2 del Camino del Sleepless. Sirve al ocultamiento y guarda secretos incluso de la realidad.',
      iconKey: 'eye-off',
      type: 'BEYONDER',
      tier: 11,
      isMajorDiscovery: true,
      revealTitle: 'El ocultamiento acepta un servidor',
      revealText: 'Aquello que proteges deja de poder ser encontrado, recordado o revelado.',
      categoryId: beyonder,
    },
    {
      slug: 'lobo',
      name: 'Lobo',
      description: 'Una criatura nocturna atraída por la vigilancia de un dominio en oscuridad.',
      iconKey: 'ghost',
      type: 'CRIATURA',
      tier: 9,
      categoryId: misticismo,
    },
    {
      slug: 'corpse-collector',
      name: 'Corpse Collector',
      description: 'Secuencia 9 del Camino de la Muerte. Reconoce las huellas que la vida deja en los muertos.',
      iconKey: 'skull',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'Los muertos conservan sus secretos',
      revealText: 'La frontera de la muerte se vuelve visible ante tus ojos.',
      categoryId: beyonder,
    },
    {
      slug: 'cadaver',
      name: 'Cadáver',
      description: 'El cuerpo que permanece cuando la muerte separa la carne del espíritu.',
      iconKey: 'skull',
      type: 'OBJETO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'tumba',
      name: 'Tumba',
      description: 'La tierra preparada para contener un cadáver y preservar su descanso.',
      iconKey: 'landmark',
      type: 'OBJETO',
      tier: 2,
      categoryId: mundano,
    },
    {
      slug: 'cementerio',
      name: 'Cementerio',
      description: 'Muchas tumbas reunidas bajo una misma frontera dedicada a los muertos.',
      iconKey: 'landmark',
      type: 'MUNDANO',
      tier: 3,
      categoryId: mundano,
    },
    {
      slug: 'muerto-viviente',
      name: 'Muerto viviente',
      description: 'Un cadáver al que un espíritu obliga a moverse pese a que la vida ya terminó.',
      iconKey: 'ghost',
      type: 'CRIATURA',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'gravedigger',
      name: 'Gravedigger',
      description: 'Secuencia 8 del Camino de la Muerte. Comprende las tumbas y los rastros dejados por los difuntos.',
      iconKey: 'mountain',
      type: 'BEYONDER',
      tier: 5,
      isMajorDiscovery: true,
      revealTitle: 'La tierra conserva a sus muertos',
      revealText: 'Cada tumba comienza a revelar lo que intentaba mantener sepultado.',
      categoryId: beyonder,
    },
    {
      slug: 'canalizacion-espiritual',
      name: 'Canalización espiritual',
      description: 'Un lenguaje usado para ofrecer al espíritu una vía de comunicación con los vivos.',
      iconKey: 'waves',
      type: 'MISTICISMO',
      tier: 4,
      categoryId: misticismo,
    },
    {
      slug: 'spirit-medium',
      name: 'Spirit Medium',
      description: 'Secuencia 7 del Camino de la Muerte. Canaliza espíritus y permite que sus voces crucen la frontera.',
      iconKey: 'ghost',
      type: 'BEYONDER',
      tier: 6,
      isMajorDiscovery: true,
      revealTitle: 'Los espíritus encuentran una voz',
      revealText: 'La muerte deja de imponer silencio a quienes sabes escuchar.',
      categoryId: beyonder,
    },
    {
      slug: 'lenguaje-de-los-muertos',
      name: 'Lenguaje de los muertos',
      description: 'Una canalización espiritual dominada hasta convertirse en la lengua de los difuntos.',
      iconKey: 'book-open',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'spirit-guide',
      name: 'Spirit Guide',
      description: 'Secuencia 6 del Camino de la Muerte. Comprende y conduce a espíritus y muertos vivientes.',
      iconKey: 'moon-star',
      type: 'BEYONDER',
      tier: 7,
      isMajorDiscovery: true,
      revealTitle: 'Los muertos reconocen un guía',
      revealText: 'Los espíritus dejan de vagar cuando tu voluntad les señala un camino.',
      categoryId: beyonder,
    },
    {
      slug: 'inframundo',
      name: 'Inframundo',
      description: 'La región del mundo espiritual donde la muerte impone sus propias leyes.',
      iconKey: 'moon',
      type: 'MISTICISMO',
      tier: 7,
      categoryId: misticismo,
    },
    {
      slug: 'puerta-al-inframundo',
      name: 'Puerta al inframundo',
      description: 'Una puerta abierta hacia las regiones espirituales gobernadas por la muerte.',
      iconKey: 'door-open',
      type: 'MISTICISMO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'limite',
      name: 'Límite',
      description: 'Una separación extendida hasta convertirse en una frontera imposible de ignorar.',
      iconKey: 'layers',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'sello',
      name: 'Sello',
      description: 'Un límite reforzado mediante simbolismo para impedir el paso entre dos regiones.',
      iconKey: 'lock-keyhole',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'gatekeeper',
      name: 'Gatekeeper',
      description: 'Secuencia 5 del Camino de la Muerte. Abre, cierra y custodia las puertas del inframundo.',
      iconKey: 'key-round',
      type: 'BEYONDER',
      tier: 8,
      isMajorDiscovery: true,
      revealTitle: 'La puerta reconoce a su guardián',
      revealText: 'El inframundo permite tu paso y acepta tu autoridad sobre sus umbrales.',
      categoryId: beyonder,
    },
    {
      slug: 'resistencia',
      name: 'Resistencia',
      description: 'El autocontrol fortalecido hasta soportar fuerzas que quebrarían a otros.',
      iconKey: 'shield',
      type: 'CONCEPTO',
      tier: 4,
      categoryId: conceptos,
    },
    {
      slug: 'resurreccion',
      name: 'Resurrección',
      description: 'La muerte obligada a permitir el retorno de aquello que ya había reclamado.',
      iconKey: 'history',
      type: 'MISTICISMO',
      tier: 6,
      categoryId: misticismo,
    },
    {
      slug: 'funeral',
      name: 'Funeral',
      description: 'Un ritual que reconoce la muerte y guía al difunto hacia su destino final.',
      iconKey: 'scroll-text',
      type: 'MISTICISMO',
      tier: 5,
      categoryId: misticismo,
    },
    {
      slug: 'undying',
      name: 'Undying',
      description: 'Secuencia 4 del Camino de la Muerte. Regresa de la muerte mediante ciclos sucesivos de resurrección.',
      iconKey: 'history',
      type: 'BEYONDER',
      tier: 9,
      isMajorDiscovery: true,
      revealTitle: 'La muerte deja de ser definitiva',
      revealText: 'El final se convierte en otra etapa de un ciclo que ahora puedes recorrer.',
      categoryId: beyonder,
    },
    {
      slug: 'ferryman',
      name: 'Ferryman',
      description: 'Secuencia 3 del Camino de la Muerte. Navega los ríos que conducen a los muertos por el inframundo.',
      iconKey: 'anchor',
      type: 'BEYONDER',
      tier: 10,
      isMajorDiscovery: true,
      revealTitle: 'El río de los muertos acepta tu rumbo',
      revealText: 'Las corrientes del inframundo obedecen a quien conoce todos sus destinos.',
      categoryId: beyonder,
    },
    {
      slug: 'autoridad',
      name: 'Autoridad',
      description: 'El orden sostenido por una dominación reconocida como legítima.',
      iconKey: 'crown',
      type: 'CONCEPTO',
      tier: 5,
      categoryId: conceptos,
    },
    {
      slug: 'autoridad-sobre-la-muerte',
      name: 'Autoridad sobre la muerte',
      description: 'Una autoridad capaz de ordenar a la muerte, sus dominios y sus habitantes.',
      iconKey: 'crown',
      type: 'MISTICISMO',
      tier: 8,
      categoryId: misticismo,
    },
    {
      slug: 'death-consul',
      name: 'Death Consul',
      description: 'Secuencia 2 del Camino de la Muerte. Ejerce autoridad directa sobre la muerte y el inframundo.',
      iconKey: 'crown',
      type: 'BEYONDER',
      tier: 11,
      isMajorDiscovery: true,
      revealTitle: 'La muerte reconoce una autoridad',
      revealText: 'Los difuntos y el inframundo reciben tus palabras como mandatos inevitables.',
      categoryId: beyonder,
    },
    {
      slug: 'savant',
      name: 'Savant',
      description: 'Secuencia 9 del Camino del Savant. Comprende las máquinas como extensiones del conocimiento.',
      iconKey: 'hammer',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'La maquinaria revela su lógica',
      revealText: 'Cada mecanismo se convierte en una idea que tus manos pueden reconstruir.',
      categoryId: beyonder,
    },
    {
      slug: 'mystery-pryer',
      name: 'Mystery Pryer',
      description: 'Secuencia 9 del Camino del Mystery Pryer. Contempla el conocimiento que se oculta tras el misterio.',
      iconKey: 'book-key',
      type: 'BEYONDER',
      tier: 4,
      isMajorDiscovery: true,
      revealTitle: 'El misterio permite una primera mirada',
      revealText: 'Lo oculto deja de ser silencio y comienza a responder a tus preguntas.',
      categoryId: beyonder,
    },
    {
      slug: 'comunidad',
      name: 'Comunidad',
      description: 'Las familias que comparten algo más que sangre.',
      iconKey: 'landmark',
      type: 'CONCEPTO',
      tier: 2,
      categoryId: conceptos,
    },
    {
      slug: 'ciudad',
      name: 'Ciudad',
      description: 'La comunidad que ya no cabe a simple vista.',
      iconKey: 'landmark',
      type: 'MUNDANO',
      tier: 3,
      categoryId: mundano,
    },
    {
      slug: 'black-knight',
      name: 'Black Knight',
      description:
        'Secuencia 4 del Camino del Suplicante de Secretos. La degeneración vestida con la disciplina de un caballero.',
      iconKey: 'moon',
      type: 'BEYONDER',
      tier: 8,
      isMajorDiscovery: true,
      revealTitle: 'La armadura ya no protege: contiene',
      revealText: 'Shepherd descubre que también la corrupción puede jurar lealtad.',
      categoryId: beyonder,
    },
    // ----- Destino, memoria, vínculos y mundos espirituales -----
    {
      slug: 'registro',
      name: 'Registro',
      description: 'Un hecho preservado para que el Archivo no lo pierda.',
      iconKey: 'file-text',
      type: 'CONCEPTO',
      tier: 0,
      // Registro ya no es inicial: se fabrica con la receta
      // observacion+diferenciacion, no mediante un
      // umbral declarativo en el propio elemento.
      categoryId: conceptos,
    },
    { slug: 'bendicion', name: 'Bendición', description: 'Una existencia oculta responde favorablemente a una plegaria o sacrificio.', iconKey: 'award', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'historia', name: 'Historia', description: 'El mundo convertido en una sucesión de registros.', iconKey: 'history', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'vinculo', name: 'Vínculo', description: 'La relación invisible que nace entre dos humanos.', iconKey: 'blend', type: 'CONCEPTO', tier: 1, categoryId: conceptos },
    { slug: 'ruptura', name: 'Ruptura', description: 'La fuerza aplicada hasta quebrar un vínculo.', iconKey: 'triangle-alert', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'separacion', name: 'Separación', description: 'La ruptura consolidada por el paso del tiempo.', iconKey: 'move-up-right', type: 'CONCEPTO', tier: 3, categoryId: conceptos },
    { slug: 'era', name: 'Era', description: 'Una continuidad tan extensa que adquiere identidad propia.', iconKey: 'hourglass', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'ausencia', name: 'Ausencia', description: 'El vacío que deja un vínculo después de la separación.', iconKey: 'eye-off', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'deseo', name: 'Deseo', description: 'La ausencia percibida se convierte en anhelo.', iconKey: 'flame', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'milagro', name: 'Milagro', description: 'Un deseo que atraviesa un cambio cualitativo y altera lo posible.', iconKey: 'wand-sparkles', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'proyeccion-astral', name: 'Proyección astral', description: 'El cuerpo espiritual proyectado más allá del plano material.', iconKey: 'orbit', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'mundo-espiritual', name: 'Mundo espiritual', description: 'El plano invisible al que conduce una proyección astral.', iconKey: 'moon-star', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'criatura-espiritual', name: 'Criatura espiritual', description: 'Una criatura adaptada a existir en el mundo espiritual.', iconKey: 'ghost', type: 'CRIATURA', tier: 5, categoryId: misticismo },
    { slug: 'descripcion-espiritual', name: 'Descripción espiritual', description: 'Un registro preciso de la esencia de una criatura espiritual.', iconKey: 'scroll-text', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'invocacion', name: 'Invocación', description: 'Un ritual capaz de llamar aquello que ha sido descrito.', iconKey: 'circle-dot-dashed', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'invocador', name: 'Invocador', description: 'Un Beyonder que domina el arte de la invocación.', iconKey: 'wand', type: 'BEYONDER', tier: 6, categoryId: beyonder },
    { slug: 'ciclo', name: 'Ciclo', description: 'El destino atrapado en una continuidad recurrente.', iconKey: 'circle-dot-dashed', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'retorno', name: 'Retorno', description: 'El ciclo que completa su recorrido a través del tiempo.', iconKey: 'history', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'consecuencia', name: 'Consecuencia', description: 'El resultado inevitable de una influencia prolongada.', iconKey: 'move-up-right', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'inevitabilidad', name: 'Inevitabilidad', description: 'La consecuencia unida al destino hasta no admitir alternativa.', iconKey: 'lock-keyhole', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'nacion', name: 'Nación', description: 'Dos ciudades unidas bajo una identidad y un destino comunes.', iconKey: 'landmark', type: 'MUNDANO', tier: 4, categoryId: mundano },
    { slug: 'simbolismo', name: 'Simbolismo', description: 'La información expresada mediante correspondencias místicas.', iconKey: 'book-key', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'mundo-astral', name: 'Mundo Astral', description: 'El dominio de los símbolos y la divinidad.', iconKey: 'star', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'rio', name: 'Río', description: 'Agua que encuentra un cauce y comienza a avanzar.', iconKey: 'waves', type: 'MUNDANO', tier: 1, categoryId: mundano },
    { slug: 'river-of-fate', name: 'River of Fate', description: 'Un río cuyo cauce sigue el destino en lugar de la geografía.', iconKey: 'waves', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'ley', name: 'Ley', description: 'El procedimiento aceptado por toda una comunidad.', iconKey: 'scroll-text', type: 'CONCEPTO', tier: 3, categoryId: conceptos },
    { slug: 'arbitro', name: 'Árbitro', description: 'Secuencia 9 del Camino del Árbitro. Su autoridad nace de aplicar la ley sobre quienes intentan desafiarla.', iconKey: 'shield', type: 'BEYONDER', tier: 4, isMajorDiscovery: true, revealTitle: 'La ley reconoce tu autoridad', revealText: 'Tu palabra adquiere el peso de una sentencia que otros no pueden ignorar.', categoryId: beyonder },
    { slug: 'pluma', name: 'Pluma', description: 'Una pluma marcada por el retorno de quien ha atravesado la muerte.', iconKey: 'feather', type: 'OBJETO', tier: 9, categoryId: misticismo },
    { slug: 'jurisdiccion', name: 'Jurisdicción', description: 'El límite dentro del cual una autoridad puede imponer sus decisiones.', iconKey: 'landmark', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'sheriff', name: 'Sheriff', description: 'Secuencia 8 del Camino del Árbitro. Extiende la autoridad sobre una jurisdicción concreta.', iconKey: 'shield', type: 'BEYONDER', tier: 5, isMajorDiscovery: true, revealTitle: 'La jurisdicción reconoce a su representante', revealText: 'La autoridad deja de ser una idea y comienza a obedecer tu presencia.', categoryId: beyonder },
    { slug: 'interrogator', name: 'Interrogator', description: 'Secuencia 7 del Camino del Árbitro. Descubre la verdad aplicando presión sobre la mente y el dolor.', iconKey: 'scan-eye', type: 'BEYONDER', tier: 6, isMajorDiscovery: true, revealTitle: 'Toda respuesta deja una grieta', revealText: 'La psique revela aquello que intentaba esconder cuando sabes dónde presionar.', categoryId: beyonder },
    { slug: 'judge', name: 'Judge', description: 'Secuencia 6 del Camino del Árbitro. Convierte la ley y la autoridad en sentencias vinculantes.', iconKey: 'scroll-text', type: 'BEYONDER', tier: 7, isMajorDiscovery: true, revealTitle: 'La sentencia adquiere fuerza', revealText: 'Tus palabras pesan como una ley que exige ser cumplida.', categoryId: beyonder },
    { slug: 'castigo', name: 'Castigo', description: 'La consecuencia establecida por la ley para quien decide quebrantarla.', iconKey: 'triangle-alert', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'investigacion', name: 'Investigación', description: 'La información guiada por el discernimiento hasta revelar una verdad oculta.', iconKey: 'scan-eye', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'disciplinary-paladin', name: 'Disciplinary Paladin', description: 'Secuencia 5 del Camino del Árbitro. Impone castigos con la disciplina de un caballero.', iconKey: 'swords', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, revealTitle: 'La disciplina empuña una sentencia', revealText: 'La ley encuentra en tu fuerza un instrumento dispuesto a ejecutarla.', categoryId: beyonder },
    { slug: 'legislacion', name: 'Legislación', description: 'La ley organizada mediante procedimientos para regular cada situación posible.', iconKey: 'book-open', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'imperative-mage', name: 'Imperative Mage', description: 'Secuencia 4 del Camino del Árbitro. Su lenguaje convierte la autoridad en órdenes inevitables.', iconKey: 'wand', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, revealTitle: 'La orden exige obediencia', revealText: 'Tus palabras dejan de persuadir y comienzan a imponer la realidad.', categoryId: beyonder },
    { slug: 'pilar', name: 'Pilar', description: 'Una estructura que permanece firme bajo la autoridad de una orden imperativa.', iconKey: 'landmark', type: 'OBJETO', tier: 9, categoryId: misticismo },
    { slug: 'caza', name: 'Caza', description: 'Una investigación respaldada por la fuerza hasta perseguir activamente a su objetivo.', iconKey: 'radar', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'chaos-hunter', name: 'Chaos Hunter', description: 'Secuencia 3 del Camino del Árbitro. Persigue y somete el desorden allí donde aparece.', iconKey: 'swords', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, revealTitle: 'El caos adquiere un perseguidor', revealText: 'Ningún desorden puede ocultarse de una caza respaldada por la autoridad.', categoryId: beyonder },
    { slug: 'equilibrio', name: 'Equilibrio', description: 'La fuerza contenida por el orden hasta sostener dos extremos sin ceder ante ninguno.', iconKey: 'layers', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'balancer', name: 'Balancer', description: 'Secuencia 2 del Camino del Árbitro. Ejerce autoridad para restaurar el equilibrio entre fuerzas opuestas.', iconKey: 'layers', type: 'BEYONDER', tier: 11, isMajorDiscovery: true, revealTitle: 'Todo extremo encuentra un contrapeso', revealText: 'La autoridad te permite decidir dónde debe descansar el equilibrio del mundo.', categoryId: beyonder },
    { slug: 'abogado', name: 'Abogado', description: 'Secuencia 9 del Camino del Abogado. Domina los procedimientos y encuentra poder en cada regla y excepción.', iconKey: 'briefcase-business', type: 'BEYONDER', tier: 4, isMajorDiscovery: true, revealTitle: 'Toda regla contiene una oportunidad', revealText: 'Comprendes que incluso la ley más firme puede inclinarse ante una interpretación precisa.', categoryId: beyonder },
    { slug: 'orden', name: 'Orden', description: 'La ley extendida sobre una ciudad.', iconKey: 'layers', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'distorsion', name: 'Distorsión', description: 'El orden deformado por la corrupción.', iconKey: 'blend', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'desorden', name: 'Desorden', description: 'La distorsión liberada por la incertidumbre.', iconKey: 'dices', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'revelacion', name: 'Revelación', description: 'La adivinación encuentra un significado oculto dentro de un dato.', iconKey: 'scan-eye', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'dato', name: 'Dato', description: 'La unidad mínima de información, fija y verificable, antes de que el tiempo le dé significado.', iconKey: 'file-digit', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'profecia', name: 'Profecía', description: 'Una revelación fijada en un registro antes de que ocurra.', iconKey: 'book-open', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'misfortune-mage', name: 'Misfortune Mage', description: 'Secuencia 4 del Camino del Monstruo. Convierte la desgracia en un arte dirigido.', iconKey: 'wand-sparkles', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'chaoswalker', name: 'Chaoswalker', description: 'Secuencia 3 del Camino del Monstruo. Camina donde el destino pierde todo orden.', iconKey: 'dices', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'soothsayer', name: 'Soothsayer', description: 'Secuencia 2 del Camino del Monstruo. Contempla los cauces futuros del destino.', iconKey: 'scan-eye', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'scholar-of-yore', name: 'Scholar of Yore', description: 'Secuencia 3 del Camino del Vidente. Extrae poder de la historia y de eras olvidadas.', iconKey: 'history', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'miracle-invoker', name: 'Invocador de Milagros', description: 'Secuencia 2 del Camino del Vidente. Hace que los deseos imposibles encuentren respuesta.', iconKey: 'wand-sparkles', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, categoryId: beyonder },
    // ----- Trinidad, profanación y el mundo de sombras -----
    { slug: 'diferenciacion', name: 'Diferenciación', description: 'La percepción que reconoce aquello que la separación vuelve distinto.', iconKey: 'layers', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'trinidad', name: 'Trinidad', description: 'Tres aspectos diferenciados que comparten una misma divinidad.', iconKey: 'triangle-alert', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'autocontrol', name: 'Autocontrol', description: 'La claridad guiada por la prudencia para dominar el propio impulso.', iconKey: 'shield', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'lenguaje', name: 'Lenguaje', description: 'Información organizada mediante un procedimiento compartido.', iconKey: 'book-open', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'profanacion', name: 'Profanación', description: 'La divinidad degradada por una degeneración persistente.', iconKey: 'triangle-alert', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'dominacion', name: 'Dominación', description: 'La fuerza ejercida a través de la influencia sobre otra voluntad.', iconKey: 'lock-keyhole', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'sombra-independiente', name: 'Sombra independiente', description: 'Una sombra separada de aquello que debía proyectarla.', iconKey: 'moon', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'sombra-dominada', name: 'Sombra dominada', description: 'Una sombra independiente sometida a una voluntad ajena.', iconKey: 'moon-star', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'continente', name: 'Continente', description: 'Dos campos extendidos hasta formar una gran masa de tierra.', iconKey: 'landmark', type: 'MUNDANO', tier: 2, categoryId: mundano },
    { slug: 'mundo', name: 'Mundo', description: 'La totalidad formada por continentes, pueblos y fronteras.', iconKey: 'orbit', type: 'MUNDANO', tier: 6, categoryId: mundano },
    { slug: 'mundo-de-sombra', name: 'Mundo de sombra', description: 'Un mundo completo cubierto por una sombra que le pertenece.', iconKey: 'moon', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'dominio-en-el-mundo-de-sombras', name: 'Dominio en el mundo de sombras', description: 'La dominación convertida en ley dentro de un mundo de sombras.', iconKey: 'key-round', type: 'MISTICISMO', tier: 8, categoryId: misticismo },
    { slug: 'trinity-templar', name: 'Trinity Templar', description: 'Secuencia 3 del Camino del Suplicante de Secretos. Encarna tres aspectos de una misma carne divina.', iconKey: 'shield', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'profane-presbyter', name: 'Profane Presbyter', description: 'Secuencia 2 del Camino del Suplicante de Secretos. Convierte la profanación en doctrina y dominio.', iconKey: 'book-key', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, categoryId: beyonder },
    // ----- Psique y Camino del Visionario -----
    { slug: 'observacion', name: 'Observación', description: 'La atención sostenida que registra sin intervenir.', iconKey: 'eye', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'pensamiento', name: 'Pensamiento', description: 'La información procesada dentro de una mente humana.', iconKey: 'brain', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'psique', name: 'Psique', description: 'El alma organizada mediante el pensamiento consciente e inconsciente.', iconKey: 'brain', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'intervencion', name: 'Intervención', description: 'Una influencia aplicada siguiendo un procedimiento preciso.', iconKey: 'move-up-right', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'sugestion', name: 'Sugestión', description: 'Un pensamiento implantado mediante influencia.', iconKey: 'waves', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'subconsciente', name: 'Subconsciente', description: 'La parte oculta de la psique que actúa sin ser percibida.', iconKey: 'eye-off', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'punto-ciego', name: 'Punto ciego', description: 'Aquello que la percepción no alcanza debido al ocultamiento.', iconKey: 'eye-off', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'invisibilidad-psicologica', name: 'Invisibilidad psicológica', description: 'Una presencia borrada de la percepción por medio de la psique.', iconKey: 'ghost', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'sueno', name: 'Sueño', description: 'Una ilusión sostenida dentro de la psique.', iconKey: 'moon-star', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'pesadilla', name: 'Pesadilla', description: 'Un sueño invadido por la percepción del peligro.', iconKey: 'moon', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'harpia', name: 'Harpía', description: 'Una criatura espiritual nacida de una pesadilla.', iconKey: 'feather', type: 'CRIATURA', tier: 6, categoryId: misticismo },
    { slug: 'contrato', name: 'Contrato', description: 'Un lenguaje fijado en un registro con voluntad de permanencia.', iconKey: 'file-text', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'contrato-con-harpia', name: 'Contrato con Harpía', description: 'Un pacto formal con una criatura de las pesadillas.', iconKey: 'scroll-text', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'alegria', name: 'Alegría', description: 'La fortuna experimentada por una mente humana.', iconKey: 'sun', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'extasis', name: 'Éxtasis', description: 'La alegría intensificada por la fuerza hasta desbordar la razón.', iconKey: 'sparkles', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'ira', name: 'Ira', description: 'La respuesta humana ante una herida.', iconKey: 'flame', type: 'CONCEPTO', tier: 3, categoryId: conceptos },
    { slug: 'furia', name: 'Furia', description: 'La ira alimentada por la fuerza hasta perder todo límite.', iconKey: 'flame', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'mar-del-subconsciente-colectivo', name: 'Mar del Subconsciente Colectivo', description: 'Los subconscientes de una comunidad unidos en una profundidad común.', iconKey: 'waves', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'multitud', name: 'Multitud', description: 'Una comunidad aumentada por la acumulación de individuos.', iconKey: 'user-round', type: 'MUNDANO', tier: 4, categoryId: mundano },
    { slug: 'gran-evento', name: 'Gran evento', description: 'Una multitud coordinada mediante un procedimiento.', iconKey: 'landmark', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'estimulo', name: 'Estímulo', description: 'Una influencia percibida por la mente y el cuerpo.', iconKey: 'radar', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'emocion', name: 'Emoción', description: 'La respuesta de la psique ante un estímulo.', iconKey: 'waves', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'emocion-colectiva', name: 'Emoción colectiva', description: 'Una emoción compartida por toda una multitud.', iconKey: 'waves', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'resonancia-emocional', name: 'Resonancia emocional', description: 'La percepción amplifica y sincroniza una emoción colectiva.', iconKey: 'radar', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'imaginacion', name: 'Imaginación', description: 'El pensamiento capaz de dar forma a una ilusión.', iconKey: 'lightbulb', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'influencia-de-sueno', name: 'Influencia de sueño', description: 'Una influencia ejercida desde el interior de un sueño.', iconKey: 'moon-star', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'discernimiento', name: 'Discernimiento', description: 'La percepción afinada por la claridad para separar lo verdadero.', iconKey: 'scan-eye', type: 'CONCEPTO', tier: 6, categoryId: conceptos },
    { slug: 'spectator', name: 'Spectator', description: 'Secuencia 9 del Camino del Visionario. Observa la conducta sin perturbarla.', iconKey: 'eye', type: 'BEYONDER', tier: 1, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'telepathist', name: 'Telepathist', description: 'Secuencia 8 del Camino del Visionario. Percibe el pensamiento ajeno.', iconKey: 'brain', type: 'BEYONDER', tier: 2, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'psychiatrist', name: 'Psychiatrist', description: 'Secuencia 7 del Camino del Visionario. Interviene directamente sobre la psique.', iconKey: 'brain', type: 'BEYONDER', tier: 3, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'hypnotist', name: 'Hypnotist', description: 'Secuencia 6 del Camino del Visionario. Implanta sugestiones en el subconsciente.', iconKey: 'eye-off', type: 'BEYONDER', tier: 4, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'dreamwalker', name: 'Dreamwalker', description: 'Secuencia 5 del Camino del Visionario. Recorre sueños y pesadillas.', iconKey: 'moon-star', type: 'BEYONDER', tier: 5, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'manipulator', name: 'Manipulator', description: 'Secuencia 4 del Camino del Visionario. Domina el subconsciente colectivo.', iconKey: 'waves', type: 'BEYONDER', tier: 6, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'dream-weaver', name: 'Dream Weaver', description: 'Secuencia 3 del Camino del Visionario. Teje imaginación y sueño en una sola realidad.', iconKey: 'wand-sparkles', type: 'BEYONDER', tier: 7, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'discerner', name: 'Discerner', description: 'Secuencia 2 del Camino del Visionario. Distingue la verdad dentro de cualquier psique.', iconKey: 'scan-eye', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, categoryId: beyonder },
    // ----- Mar, tormentas y Camino del Tirano -----
    { slug: 'dolor', name: 'Dolor', description: 'La percepción consciente de una herida o una pérdida.', iconKey: 'bandage', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'carta-nautica', name: 'Carta náutica', description: 'El mar convertido en un registro de rutas y peligros.', iconKey: 'file-text', type: 'OBJETO', tier: 3, categoryId: mundano },
    { slug: 'navegacion', name: 'Navegación', description: 'La percepción aplicada a la lectura de una carta náutica.', iconKey: 'radar', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'magia-acuatica', name: 'Magia acuática', description: 'La magia que fluye y adopta las propiedades del agua.', iconKey: 'droplets', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'tormenta', name: 'Tormenta', description: 'El mar agitado por una calamidad.', iconKey: 'cloud-lightning', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'viento', name: 'Viento', description: 'La parte aérea de una tormenta después de separarse.', iconKey: 'wind', type: 'MUNDANO', tier: 3, categoryId: mundano },
    { slug: 'lluvia', name: 'Lluvia', description: 'El agua que una tormenta separa del cielo.', iconKey: 'cloud-rain', type: 'MUNDANO', tier: 3, categoryId: mundano },
    { slug: 'relampago', name: 'Relámpago', description: 'La luz concentrada y liberada por una tormenta.', iconKey: 'zap', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'obninsk', name: 'Obninsk', description: 'Una criatura Beyonder acuática transformada por la devoración.', iconKey: 'anchor', type: 'CRIATURA', tier: 7, categoryId: misticismo },
    { slug: 'rey', name: 'Rey', description: 'La dominación reconocida por toda una comunidad.', iconKey: 'crown', type: 'CONCEPTO', tier: 5, categoryId: conceptos },
    { slug: 'construccion', name: 'Construcción', description: 'El trabajo convertido en un procedimiento capaz de levantar estructuras.', iconKey: 'hammer', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'torre', name: 'Torre', description: 'Una construcción extendida hacia lo alto.', iconKey: 'landmark', type: 'OBJETO', tier: 5, categoryId: mundano },
    { slug: 'oficiante', name: 'Oficiante', description: 'El humano que aprende a conducir un ritual.', iconKey: 'scroll-text', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'tierra', name: 'Tierra', description: 'El elemento firme bajo toda construcción y toda frontera.', iconKey: 'mountain', type: 'MUNDANO', tier: 0, isStarter: true, isHiddenUntilDiscovered: false, categoryId: mundano },
    { slug: 'campo', name: 'Campo', description: 'La tierra trabajada y extendida hasta adquirir una forma propia.', iconKey: 'sprout', type: 'MUNDANO', tier: 1, categoryId: mundano },
    { slug: 'espacio', name: 'Espacio', description: 'La extensión donde toda posición, distancia y movimiento pueden existir.', iconKey: 'orbit', type: 'CONCEPTO', tier: 0, categoryId: conceptos },
    { slug: 'vacio', name: 'Vacío', description: 'El espacio privado de toda materia, presencia y dirección.', iconKey: 'circle', type: 'CONCEPTO', tier: 1, categoryId: conceptos },
    { slug: 'apertura', name: 'Apertura', description: 'Una separación extendida en el espacio hasta permitir el paso.', iconKey: 'door-open', type: 'MISTICISMO', tier: 3, categoryId: misticismo },
    { slug: 'puerta', name: 'Puerta', description: 'La tierra delimitando un espacio que puede abrirse o cerrarse.', iconKey: 'key-round', type: 'OBJETO', tier: 1, categoryId: mundano },
    { slug: 'aprendiz', name: 'Aprendiz', description: 'Secuencia 9 del Camino de la Puerta. Quien ha aprendido a encontrar puertas donde otros solo ven límites.', iconKey: 'book-open', type: 'BEYONDER', tier: 4, isMajorDiscovery: true, revealTitle: 'Una puerta se abre', revealText: 'El vacío al otro lado te reconoce como alguien dispuesto a aprender.', categoryId: beyonder },
    { slug: 'truco', name: 'Truco', description: 'Una ilusión manipulada con suficiente precisión para producir un efecto imposible.', iconKey: 'wand-sparkles', type: 'MISTICISMO', tier: 4, categoryId: misticismo },
    { slug: 'trickmaster', name: 'Trickmaster', description: 'Secuencia 8 del Camino de la Puerta. Convierte cada apertura en escenario para un truco imposible.', iconKey: 'sparkles', type: 'BEYONDER', tier: 5, isMajorDiscovery: true, revealTitle: 'El espacio aprende el truco', revealText: 'Las puertas ya no limitan tu camino: ahora forman parte de la función.', categoryId: beyonder },
    { slug: 'espacio-exterior', name: 'Espacio exterior', description: 'El vacío extendido más allá de toda frontera terrestre.', iconKey: 'orbit', type: 'CONCEPTO', tier: 2, categoryId: conceptos },
    { slug: 'cuerpo-celeste', name: 'Cuerpo celeste', description: 'Una presencia distinguible al observar el espacio exterior.', iconKey: 'moon-star', type: 'CONCEPTO', tier: 3, categoryId: conceptos },
    { slug: 'astrologo', name: 'Astrólogo', description: 'Secuencia 7 del Camino de la Puerta. Lee rutas y presagios en los cuerpos celestes.', iconKey: 'telescope', type: 'BEYONDER', tier: 6, isMajorDiscovery: true, revealTitle: 'El firmamento revela una ruta', revealText: 'Cada estrella se convierte en coordenada para una puerta aún distante.', categoryId: beyonder },
    { slug: 'poder-beyonder', name: 'Poder Beyonder', description: 'La fuerza que surge cuando el misticismo encuentra una naturaleza Beyonder.', iconKey: 'sparkles', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'escriba', name: 'Escriba', description: 'Secuencia 6 del Camino de la Puerta. Registra poderes Beyonder para reproducir sus efectos.', iconKey: 'scroll-text', type: 'BEYONDER', tier: 7, isMajorDiscovery: true, revealTitle: 'La página conserva el poder', revealText: 'Lo imposible deja una marca que ahora puedes volver a invocar.', categoryId: beyonder },
    { slug: 'traveler', name: 'Traveler', description: 'Secuencia 5 del Camino de la Puerta. Cruza distancias que otros ni siquiera reconocen como transitables.', iconKey: 'footprints', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, revealTitle: 'El camino se abre bajo tus pies', revealText: 'Las fronteras del mundo se vuelven sugerencias que ya no te detienen.', categoryId: beyonder },
    { slug: 'secrets-sorcerer', name: 'Secrets Sorcerer', description: 'Secuencia 4 del Camino de la Puerta. Abre pasadizos ocultos entre lo vedado y lo olvidado.', iconKey: 'book-key', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, revealTitle: 'Los secretos tienen puertas', revealText: 'Cada cerradura desconocida responde a una llave que solo tú sabes encontrar.', categoryId: beyonder },
    { slug: 'wanderer', name: 'Wanderer', description: 'Secuencia 3 del Camino de la Puerta. Deambula por los planos intermedios sin perderse del todo.', iconKey: 'orbit', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, revealTitle: 'Ya no hay un solo camino', revealText: 'El espacio entre los mundos se convierte en tu territorio natural.', categoryId: beyonder },
    { slug: 'planeswalker', name: 'Planeswalker', description: 'Secuencia 2 del Camino de la Puerta. Traspasa realidades como quien cruza un umbral familiar.', iconKey: 'layers', type: 'BEYONDER', tier: 11, isMajorDiscovery: true, revealTitle: 'Los planos se doblan ante ti', revealText: 'La distinción entre aquí y allá se disuelve en una sola puerta.', categoryId: beyonder },
    { slug: 'robo', name: 'Robo', description: 'La apropiación de aquello que pertenecía a otro.', iconKey: 'hand', type: 'CONCEPTO', tier: 4, categoryId: conceptos },
    { slug: 'marauder', name: 'Marauder', description: 'Secuencia 9 del Camino del Error. Encuentra oportunidades donde otros solo ven propiedad.', iconKey: 'hand', type: 'BEYONDER', tier: 5, isMajorDiscovery: true, revealTitle: 'Nada está completamente protegido', revealText: 'Tus ojos reconocen el instante exacto en que algo puede ser tomado.', categoryId: beyonder },
    { slug: 'swindler', name: 'Swindler', description: 'Secuencia 8 del Camino del Error. Convierte la fortuna y el engaño en herramientas de estafa.', iconKey: 'dices', type: 'BEYONDER', tier: 6, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'cryptologist', name: 'Cryptologist', description: 'Secuencia 7 del Camino del Error. Descifra los datos ocultos tras símbolos y secretos místicos.', iconKey: 'file-key', type: 'BEYONDER', tier: 7, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'prometheus', name: 'Prometheus', description: 'Secuencia 6 del Camino del Error. Se apropia del poder Beyonder como si fuera fuego robado.', iconKey: 'flame', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'robo-de-identidad', name: 'Robo de identidad', description: 'El robo aplicado a aquello que hace única a una persona.', iconKey: 'scan-face', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'blasfemia', name: 'Blasfemia', description: 'Una identidad robada que se atreve a usurpar lo divino.', iconKey: 'triangle-alert', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'dream-stealer', name: 'Dream Stealer', description: 'Secuencia 5 del Camino del Error. Roba sueños, pensamientos e identidades mientras sus víctimas duermen.', iconKey: 'moon-star', type: 'BEYONDER', tier: 9, isMajorDiscovery: true, revealTitle: 'El sueño deja de pertenecerte', revealText: 'Las fronteras de la mente se abren ante una mano que sabe robar sin despertar.', categoryId: beyonder },
    { slug: 'parasitismo', name: 'Parasitismo', description: 'El robo de un cuerpo espiritual convertido en una forma de existencia dependiente.', iconKey: 'ghost', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'avatar', name: 'Avatar', description: 'Un cuerpo espiritual ocupado y modelado por el parasitismo hasta representar otra voluntad.', iconKey: 'user-round', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'parasite', name: 'Parasite', description: 'Secuencia 4 del Camino del Error. Invade cuerpos y voluntades para existir a través de otros.', iconKey: 'ghost', type: 'BEYONDER', tier: 10, isMajorDiscovery: true, revealTitle: 'Otra existencia se convierte en refugio', revealText: 'El límite entre tu voluntad y el cuerpo ajeno deja de ser una barrera.', categoryId: beyonder },
    { slug: 'engano', name: 'Engaño', description: 'Información convertida en un truco capaz de presentar la falsedad como verdad.', iconKey: 'blend', type: 'MISTICISMO', tier: 5, categoryId: misticismo },
    { slug: 'laguna', name: 'Laguna', description: 'Un punto ciego dentro de la ley que permite escapar de sus límites.', iconKey: 'circle-help', type: 'MISTICISMO', tier: 6, categoryId: misticismo },
    { slug: 'mentor-of-deceit', name: 'Mentor of Deceit', description: 'Secuencia 3 del Camino del Error. Convierte engaños y contradicciones en reglas que otros aceptan.', iconKey: 'book-key', type: 'BEYONDER', tier: 11, isMajorDiscovery: true, revealTitle: 'La mentira adquiere autoridad', revealText: 'Las reglas dejan de describir la realidad y comienzan a obedecer tu engaño.', categoryId: beyonder },
    { slug: 'suplantacion', name: 'Suplantación', description: 'Un disfraz sostenido por el engaño hasta ocupar por completo una identidad ajena.', iconKey: 'drama', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'trojan-horse-of-destiny', name: 'Trojan Horse of Destiny', description: 'Secuencia 2 del Camino del Error. Se infiltra en el destino ajeno para sustituirlo desde dentro.', iconKey: 'dices', type: 'BEYONDER', tier: 12, isMajorDiscovery: true, revealTitle: 'El destino admite un intruso', revealText: 'Tu identidad se oculta dentro del destino ajeno hasta que ambos resultan indistinguibles.', categoryId: beyonder },
    { slug: 'terremoto', name: 'Terremoto', description: 'La tierra sacudida por una calamidad.', iconKey: 'activity', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'tsunami', name: 'Tsunami', description: 'El mar elevado por una calamidad hasta devorar la costa.', iconKey: 'waves', type: 'MISTICISMO', tier: 7, categoryId: misticismo },
    { slug: 'sailor', name: 'Sailor', description: 'Secuencia 9 del Camino del Tirano. Su cuerpo aprende a obedecer al mar.', iconKey: 'anchor', type: 'BEYONDER', tier: 1, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'folk-of-rage', name: 'Folk of Rage', description: 'Secuencia 8 del Camino del Tirano. Convierte la ira en fuerza oceánica.', iconKey: 'flame', type: 'BEYONDER', tier: 2, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'seafarer', name: 'Seafarer', description: 'Secuencia 7 del Camino del Tirano. Navega mediante magia acuática.', iconKey: 'radar', type: 'BEYONDER', tier: 3, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'wind-blessed', name: 'Wind-blessed', description: 'Secuencia 6 del Camino del Tirano. Recibe la bendición del viento.', iconKey: 'wind', type: 'BEYONDER', tier: 4, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'ocean-songster', name: 'Ocean Songster', description: 'Secuencia 5 del Camino del Tirano. Su canto lleva la voz del relámpago.', iconKey: 'music', type: 'BEYONDER', tier: 5, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'cataclysmic-interrer', name: 'Cataclysmic Interrer', description: 'Secuencia 4 del Camino del Tirano. Oficia terremotos y tsunamis como rituales.', iconKey: 'cloud-lightning', type: 'BEYONDER', tier: 6, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'sea-king', name: 'Sea King', description: 'Secuencia 3 del Camino del Tirano. Reina sobre el mar desde su dominio.', iconKey: 'crown', type: 'BEYONDER', tier: 7, isMajorDiscovery: true, categoryId: beyonder },
    { slug: 'calamity', name: 'Calamidad', description: 'Secuencia 2 del Camino del Tirano. Convierte el mar y la tormenta en desastres capaces de arrasar naciones.', iconKey: 'cloud-lightning', type: 'BEYONDER', tier: 8, isMajorDiscovery: true, revealTitle: 'La tormenta se convierte en calamidad', revealText: 'El cielo y el mar reconocen en ti una fuerza capaz de devastar el mundo.', categoryId: beyonder },
  ]
}
