export type RecipeSeed = {
  ings: [string, number][]
  outputs: string[]
  // Por defecto true. Las recetas reservadas para una fase futura se
  // declaran con `isActive: false` para no distorsionar el grafo publicado.
  isActive?: boolean
}

export function getRecipeDefinitions(): RecipeSeed[] {
  return [
    // Camino del Vidente
    { ings: [['ojo', 2]], outputs: ['vision'] },
    { ings: [['vision', 1], ['ojo', 1]], outputs: ['percepcion', 'observacion'] },
    { ings: [['registro', 1], ['percepcion', 1]], outputs: ['dato'] },
    { ings: [['moneda', 2]], outputs: ['fortuna'] },
    { ings: [['fortuna', 1], ['moneda', 1]], outputs: ['adivinacion'] },
    { ings: [['adivinacion', 1], ['percepcion', 1]], outputs: ['seer'] },
    { ings: [['mundo', 1], ['registro', 1]], outputs: ['historia'] },
    { ings: [['adivinacion', 1], ['dato', 1]], outputs: ['revelacion'] },
    // Camino del Suplicante de Secretos
    { ings: [['humano', 2]], outputs: ['vinculo'] },
    { ings: [['secreto', 1], ['humano', 1]], outputs: ['secret-suplicant'] },
    // Camino del Monstruo
    { ings: [['humano', 1], ['moneda', 1]], outputs: ['trabajo'] },
    // Cadena del Ocultamiento
    // TODO(PHASE_4): redesign and reactivate only when Phase 4 progression is implemented.
    { ings: [['experiencia-2', 1], ['conocimiento', 1]], outputs: ['prudencia'], isActive: false },
    { ings: [['prudencia', 1], ['informacion', 1]], outputs: ['reserva'] },
    { ings: [['reserva', 1], ['vision', 1]], outputs: ['ocultamiento'] },
    // Trabajo, peligro y control corporal
    { ings: [['trabajo', 1], ['tiempo', 1]], outputs: ['esfuerzo'] },
    { ings: [['humano', 1], ['esfuerzo', 1]], outputs: ['desgaste'] },
    { ings: [['muerte', 1], ['percepcion', 1]], outputs: ['peligro'] },
    { ings: [['peligro', 1], ['intuicion', 1]], outputs: ['danger-intuition'] },
    { ings: [['fuerza', 1], ['experiencia-2', 1]], outputs: ['control-corporal'] },
    {
      ings: [['peligro', 1], ['misticismo', 1]],
      outputs: ['existencia-oculta', 'revelacion-prohibida'],
    },
    { ings: [['revelacion-prohibida', 1], ['humano', 1]], outputs: ['locura'] },
    // Escucha, magia, incertidumbre y suerte
    { ings: [['humano', 1], ['percepcion', 1]], outputs: ['escucha'] },
    // TODO(PHASE_4): redesign and reactivate only when Phase 4 progression is implemented.
    { ings: [['misticismo', 1], ['conocimiento', 1]], outputs: ['magia'], isActive: false },
    { ings: [['percepcion', 1], ['magia', 1]], outputs: ['ilusion'] },
    { ings: [['adivinacion', 1], ['tiempo', 1]], outputs: ['destino'] },
    { ings: [['informacion', 1], ['ocultamiento', 1]], outputs: ['incertidumbre', 'secreto'] },
    { ings: [['destino', 1], ['incertidumbre', 1]], outputs: ['suerte'] },
    // Cambio cualitativo, sombras y carne
    { ings: [['beyonder', 1], ['revelacion', 1]], outputs: ['avance'] },
    { ings: [['avance', 1], ['fuerza', 1]], outputs: ['cambio-cualitativo'] },
    {
      ings: [['secuencia-media', 1], ['cambio-cualitativo', 1]],
      outputs: ['divinidad', 'saint', 'demigod'],
    },
    { ings: [['cambio-cualitativo', 1], ['demigod', 1]], outputs: ['angel'] },
    // TODO(PHASE_4): redesign and reactivate only when Phase 4 progression is implemented.
    { ings: [['conocimiento', 1], ['percepcion', 1]], outputs: ['claridad'], isActive: false },
    { ings: [['claridad', 1], ['misticismo', 1]], outputs: ['luz'] },
    { ings: [['luz', 1], ['canto', 1]], outputs: ['bard'] },
    { ings: [['luz', 1], ['fuerza', 1]], outputs: ['fuego'] },
    { ings: [['registro', 1], ['ley', 1]], outputs: ['contrato'] },
    { ings: [['bendicion', 1], ['corrupcion', 1]], outputs: ['purificacion'] },
    { ings: [['agua', 1], ['fuerza', 1]], outputs: ['hielo'] },
    { ings: [['hielo', 1], ['continuidad', 1]], outputs: ['hielo-eterno'] },
    { ings: [['sombra', 1], ['ocultamiento', 1]], outputs: ['oscuridad'] },
    { ings: [['ley', 1], ['discernimiento', 1]], outputs: ['justicia'] },
    { ings: [['justicia', 1], ['contrato', 1]], outputs: ['codigos'] },
    { ings: [['construccion', 1], ['misticismo', 1]], outputs: ['artefacto'] },
    { ings: [['divinidad', 1], ['luz', 1]], outputs: ['autoridad-solar'] },
    { ings: [['autoridad-solar', 1], ['artefacto', 1]], outputs: ['reliquia-solar'] },
    { ings: [['experiencia-2', 1], ['registro', 1]], outputs: ['memoria'] },
    { ings: [['vision', 1], ['ocultamiento', 1]], outputs: ['silueta'] },
    { ings: [['silueta', 1], ['luz', 1]], outputs: ['sombra'] },
    { ings: [['peligro', 1], ['cambio-cualitativo', 1]], outputs: ['calamidad'] },
    { ings: [['peligro', 1], ['fuerza', 1]], outputs: ['desastre'] },
    { ings: [['humano', 1], ['ocultamiento', 1]], outputs: ['disfraz'] },
    { ings: [['humano', 1], ['muerte', 1]], outputs: ['carne', 'espiritu', 'cadaver'] },
    // Camino de la Muerte
    { ings: [['cadaver', 1], ['espiritu', 1]], outputs: ['corpse-collector', 'muerto-viviente'] },
    { ings: [['cadaver', 1], ['tierra', 1]], outputs: ['tumba'] },
    { ings: [['tumba', 2]], outputs: ['cementerio'] },
    { ings: [['espiritu', 1], ['lenguaje', 1]], outputs: ['canalizacion-espiritual'] },
    {
      ings: [['canalizacion-espiritual', 1], ['dominacion', 1]],
      outputs: ['lenguaje-de-los-muertos'],
    },
    { ings: [['mundo-espiritual', 1], ['muerte', 1]], outputs: ['inframundo'] },
    { ings: [['puerta', 1], ['inframundo', 1]], outputs: ['puerta-al-inframundo'] },
    { ings: [['extension', 1], ['separacion', 1]], outputs: ['limite'] },
    { ings: [['limite', 1], ['simbolismo', 1]], outputs: ['sello'] },
    { ings: [['autocontrol', 1], ['fuerza', 1]], outputs: ['resistencia'] },
    { ings: [['muerte', 1], ['retorno', 1]], outputs: ['resurreccion'] },
    { ings: [['muerte', 1], ['ritual', 1]], outputs: ['funeral'] },
    { ings: [['orden', 1], ['dominacion', 1]], outputs: ['autoridad'] },
    {
      ings: [['autoridad', 1], ['muerte', 1]],
      outputs: ['autoridad-sobre-la-muerte'],
    },
    { ings: [['carne', 1], ['fuerza', 1]], outputs: ['herida'] },
    { ings: [['carne', 1], ['herida', 1]], outputs: ['sangre'] },
    { ings: [['carne', 1], ['sangre', 1]], outputs: ['carne-y-sangre'] },
    { ings: [['espiritu', 1], ['experiencia-2', 1]], outputs: ['alma'] },
    { ings: [['desgaste', 1], ['tiempo', 1]], outputs: ['hambre'] },
    { ings: [['hambre', 1], ['carne', 1]], outputs: ['devoracion'] },
    { ings: [['informacion', 1], ['percepcion', 1]], outputs: ['influencia'] },
    // El peso del tiempo: edad, vejez y conocimiento acumulado
    { ings: [['humano', 1], ['tiempo', 1]], outputs: ['edad'] },
    { ings: [['edad', 1], ['desgaste', 1]], outputs: ['vejez'] },
    { ings: [['humano', 1], ['vejez', 1]], outputs: ['experiencia-2'] },
    { ings: [['experiencia-2', 1], ['dato', 1]], outputs: ['conocimiento'] },
    // TODO(PHASE_4): redesign and reactivate only when Phase 4 progression is implemented.
    { ings: [['conocimiento', 1], ['dato', 1]], outputs: ['informacion'], isActive: false },
    // Cadena del Mar y la Sirena
    { ings: [['moneda', 1], ['tiempo', 1]], outputs: ['acumulacion'] },
    { ings: [['agua', 1], ['acumulacion', 1]], outputs: ['mar'] },
    { ings: [['carne', 1], ['alma', 1]], outputs: ['criatura'] },
    { ings: [['criatura', 1], ['beyonder', 1]], outputs: ['criatura-beyonder'] },
    { ings: [['escucha', 1], ['tiempo', 1]], outputs: ['ritmo'] },
    { ings: [['ritmo', 1], ['humano', 1]], outputs: ['canto'] },
    { ings: [['criatura-beyonder', 1], ['mar', 1]], outputs: ['criatura-beyonder-acuatica'] },
    { ings: [['criatura-beyonder-acuatica', 1], ['canto', 1]], outputs: ['sirena'] },
    // Cadena del Cuerpo Espiritual y la Marioneta
    { ings: [['humano', 1], ['misticismo', 1]], outputs: ['espiritualidad'] },
    { ings: [['misticismo', 1], ['percepcion', 1]], outputs: ['percepcion-espiritual'] },
    { ings: [['espiritualidad', 1], ['percepcion', 1]], outputs: ['intuicion'] },
    { ings: [['intuicion', 1], ['percepcion-espiritual', 1]], outputs: ['monster'] },
    { ings: [['misticismo', 1], ['vision', 1]], outputs: ['vision-espiritual'] },
    { ings: [['tiempo', 2]], outputs: ['continuidad'] },
    { ings: [['silueta', 1], ['avance', 1]], outputs: ['proyeccion'] },
    { ings: [['proyeccion', 1], ['continuidad', 1]], outputs: ['extension'] },
    { ings: [['cuerpo-espiritual', 1], ['extension', 1]], outputs: ['hilos-del-cuerpo-espiritual'] },
    { ings: [['hilos-del-cuerpo-espiritual', 1], ['influencia', 1]], outputs: ['marioneta'] },
    { ings: [['suerte', 1], ['desastre', 1]], outputs: ['mala-suerte'] },
    { ings: [['informacion', 1], ['trabajo', 1]], outputs: ['procedimiento'] },
    { ings: [['procedimiento', 1], ['misticismo', 1]], outputs: ['ritual'] },
    { ings: [['ritual', 1], ['existencia-oculta', 1]], outputs: ['rezar', 'sacrificio', 'otorgamiento'] },
    // Bendición y memoria histórica
    { ings: [['existencia-oculta', 1], ['sacrificio', 1]], outputs: ['bendicion'] },
    { ings: [['existencia-oculta', 1], ['rezar', 1]], outputs: ['bendicion'] },
    // Vínculos, separación y milagros
    { ings: [['vinculo', 1], ['fuerza', 1]], outputs: ['ruptura'] },
    { ings: [['continuidad', 1], ['tiempo', 1]], outputs: ['era'] },
    { ings: [['vinculo', 1], ['separacion', 1]], outputs: ['ausencia'] },
    { ings: [['ausencia', 1], ['percepcion', 1]], outputs: ['deseo'] },
    { ings: [['deseo', 1], ['cambio-cualitativo', 1]], outputs: ['milagro'] },
    // Mundo espiritual e invocación
    { ings: [['cuerpo-espiritual', 1], ['proyeccion', 1]], outputs: ['proyeccion-astral'] },
    { ings: [['proyeccion-astral', 1], ['misticismo', 1]], outputs: ['mundo-espiritual'] },
    { ings: [['mundo-espiritual', 1], ['criatura', 1]], outputs: ['criatura-espiritual'] },
    { ings: [['criatura-espiritual', 1], ['registro', 1]], outputs: ['descripcion-espiritual'] },
    { ings: [['descripcion-espiritual', 1], ['ritual', 1]], outputs: ['invocacion'] },
    { ings: [['beyonder', 1], ['invocacion', 1]], outputs: ['invocador'] },
    // Destino, ley y los planos superiores
    { ings: [['destino', 1], ['continuidad', 1]], outputs: ['ciclo'] },
    { ings: [['ciclo', 1], ['tiempo', 1]], outputs: ['retorno'] },
    { ings: [['influencia', 1], ['tiempo', 1]], outputs: ['consecuencia'] },
    { ings: [['consecuencia', 1], ['destino', 1]], outputs: ['inevitabilidad'] },
    { ings: [['ciudad', 2]], outputs: ['nacion'] },
    { ings: [['informacion', 1], ['misticismo', 1]], outputs: ['simbolismo'] },
    { ings: [['simbolismo', 1], ['divinidad', 1]], outputs: ['mundo-astral'] },
    { ings: [['agua', 2]], outputs: ['rio'] },
    { ings: [['rio', 1], ['destino', 1]], outputs: ['river-of-fate'] },
    { ings: [['comunidad', 1], ['procedimiento', 1]], outputs: ['ley'] },
    { ings: [['influencia', 1], ['ley', 1]], outputs: ['arbitro'] },
    { ings: [['limite', 1], ['autoridad', 1]], outputs: ['jurisdiccion'] },
    { ings: [['herida', 1], ['percepcion', 1]], outputs: ['dolor'] },
    { ings: [['ley', 1], ['consecuencia', 1]], outputs: ['castigo'] },
    { ings: [['informacion', 1], ['discernimiento', 1]], outputs: ['investigacion'] },
    { ings: [['ley', 1], ['procedimiento', 1]], outputs: ['legislacion'] },
    { ings: [['investigacion', 1], ['fuerza', 1]], outputs: ['caza'] },
    { ings: [['fuerza', 1], ['orden', 1]], outputs: ['equilibrio'] },
    { ings: [['oscuridad', 1], ['extension', 1]], outputs: ['noche'] },
    { ings: [['autocontrol', 1], ['sueno', 1]], outputs: ['vigilia'] },
    { ings: [['lenguaje', 1], ['ritmo', 1]], outputs: ['poesia'] },
    { ings: [['canto', 1], ['muerte', 1]], outputs: ['requiem'] },
    { ings: [['noche', 1], ['vigilia', 1]], outputs: ['sleepless'] },
    { ings: [['humano', 1], ['diferenciacion', 1]], outputs: ['identidad'] },
    { ings: [['jurisdiccion', 1], ['misticismo', 1]], outputs: ['dominio'] },
    { ings: [['vinculo', 1], ['continuidad', 1]], outputs: ['linaje'] },
    { ings: [['pesadilla', 1], ['psique', 1]], outputs: ['horror'] },
    { ings: [['autocontrol', 1], ['peligro', 1]], outputs: ['valor'] },
    { ings: [['ley', 1], ['ciudad', 1]], outputs: ['orden'] },
    { ings: [['orden', 1], ['corrupcion', 1]], outputs: ['distorsion'] },
    { ings: [['distorsion', 1], ['incertidumbre', 1]], outputs: ['desorden'] },
    { ings: [['revelacion', 1], ['registro', 1]], outputs: ['profecia'] },
    // Trinidad, profanación y dominio de sombras
    { ings: [['percepcion', 1], ['separacion', 1]], outputs: ['diferenciacion'] },
    { ings: [['diferenciacion', 1], ['divinidad', 1]], outputs: ['trinidad'] },
    { ings: [['claridad', 1], ['prudencia', 1]], outputs: ['autocontrol'] },
    { ings: [['informacion', 1], ['procedimiento', 1]], outputs: ['lenguaje'] },
    { ings: [['divinidad', 1], ['degeneracion', 1]], outputs: ['profanacion'] },
    { ings: [['fuerza', 1], ['influencia', 1]], outputs: ['dominacion'] },
    { ings: [['sombra', 1], ['separacion', 1]], outputs: ['sombra-independiente'] },
    { ings: [['sombra-independiente', 1], ['dominacion', 1]], outputs: ['sombra-dominada'] },
    { ings: [['tierra', 2]], outputs: ['campo'] },
    { ings: [['campo', 2]], outputs: ['continente'] },
    // Camino de la Puerta
    { ings: [['espacio', 2]], outputs: ['vacio'] },
    { ings: [['espacio', 1], ['vacio', 1]], outputs: ['separacion'] },
    { ings: [['separacion', 1], ['espacio', 1]], outputs: ['apertura'] },
    { ings: [['tierra', 1], ['espacio', 1]], outputs: ['puerta'] },
    { ings: [['puerta', 1], ['apertura', 1]], outputs: ['aprendiz'] },
    { ings: [['percepcion', 1], ['vacio', 1]], outputs: ['ilusion'] },
    { ings: [['percepcion', 1], ['ilusion', 1]], outputs: ['truco'] },
    { ings: [['vacio', 2]], outputs: ['espacio-exterior'] },
    { ings: [['espacio-exterior', 1], ['observacion', 1]], outputs: ['cuerpo-celeste'] },
    { ings: [['beyonder', 1], ['misticismo', 1]], outputs: ['poder-beyonder'] },
    // Camino del Error
    { ings: [['separacion', 1], ['moneda', 1]], outputs: ['robo'] },
    { ings: [['robo', 1], ['percepcion', 1]], outputs: ['marauder'] },
    { ings: [['humano', 1], ['robo', 1]], outputs: ['robo-de-identidad'] },
    { ings: [['robo-de-identidad', 1], ['divinidad', 1]], outputs: ['blasfemia'] },
    { ings: [['robo', 1], ['cuerpo-espiritual', 1]], outputs: ['parasitismo'] },
    { ings: [['parasitismo', 1], ['cuerpo-espiritual', 1]], outputs: ['avatar'] },
    { ings: [['informacion', 1], ['truco', 1]], outputs: ['engano'] },
    { ings: [['punto-ciego', 1], ['ley', 1]], outputs: ['laguna'] },
    { ings: [['disfraz', 1], ['engano', 1]], outputs: ['suplantacion'] },
    { ings: [['continente', 2]], outputs: ['mundo'] },
    { ings: [['mundo', 1], ['sombra', 1]], outputs: ['mundo-de-sombra'] },
    { ings: [['mundo-de-sombra', 1], ['dominacion', 1]], outputs: ['dominio-en-el-mundo-de-sombras'] },
    // Psique, emociones y Camino del Visionario
    { ings: [['observacion', 1], ['prudencia', 1]], outputs: ['spectator'] },
    { ings: [['humano', 1], ['informacion', 1]], outputs: ['pensamiento'] },
    { ings: [['alma', 1], ['pensamiento', 1]], outputs: ['psique'] },
    { ings: [['influencia', 1], ['procedimiento', 1]], outputs: ['abogado', 'intervencion'] },
    { ings: [['pensamiento', 1], ['influencia', 1]], outputs: ['sugestion'] },
    { ings: [['psique', 1], ['ocultamiento', 1]], outputs: ['subconsciente'] },
    { ings: [['percepcion', 1], ['ocultamiento', 1]], outputs: ['punto-ciego'] },
    { ings: [['punto-ciego', 1], ['psique', 1]], outputs: ['invisibilidad-psicologica'] },
    { ings: [['psique', 1], ['ilusion', 1]], outputs: ['sueno'] },
    { ings: [['sueno', 1], ['peligro', 1]], outputs: ['pesadilla'] },
    { ings: [['cuerpo-espiritual', 1], ['criatura', 1]], outputs: ['criatura-espiritual'] },
    { ings: [['criatura-espiritual', 1], ['pesadilla', 1]], outputs: ['harpia'] },
    { ings: [['lenguaje', 1], ['registro', 1]], outputs: ['contrato'] },
    { ings: [['harpia', 1], ['contrato', 1]], outputs: ['contrato-con-harpia'] },
    { ings: [['humano', 1], ['fortuna', 1]], outputs: ['alegria'] },
    { ings: [['alegria', 1], ['fuerza', 1]], outputs: ['extasis'] },
    { ings: [['humano', 1], ['herida', 1]], outputs: ['ira'] },
    { ings: [['ira', 1], ['fuerza', 1]], outputs: ['furia'] },
    { ings: [['subconsciente', 1], ['comunidad', 1]], outputs: ['mar-del-subconsciente-colectivo'] },
    { ings: [['comunidad', 1], ['acumulacion', 1]], outputs: ['multitud'] },
    { ings: [['multitud', 1], ['procedimiento', 1]], outputs: ['gran-evento'] },
    { ings: [['percepcion', 1], ['influencia', 1]], outputs: ['estimulo'] },
    { ings: [['psique', 1], ['estimulo', 1]], outputs: ['emocion'] },
    { ings: [['emocion', 1], ['multitud', 1]], outputs: ['emocion-colectiva'] },
    { ings: [['emocion-colectiva', 1], ['percepcion', 1]], outputs: ['resonancia-emocional'] },
    { ings: [['pensamiento', 1], ['ilusion', 1]], outputs: ['imaginacion'] },
    { ings: [['sueno', 1], ['influencia', 1]], outputs: ['influencia-de-sueno'] },
    { ings: [['percepcion', 1], ['claridad', 1]], outputs: ['discernimiento'] },
    // Mar, tormentas y Camino del Tirano
    { ings: [['mar', 1], ['control-corporal', 1]], outputs: ['sailor'] },
    { ings: [['dolor', 1], ['humano', 1]], outputs: ['ira'] },
    { ings: [['mar', 1], ['registro', 1]], outputs: ['carta-nautica'] },
    { ings: [['carta-nautica', 1], ['percepcion', 1]], outputs: ['navegacion'] },
    { ings: [['agua', 1], ['magia', 1]], outputs: ['magia-acuatica'] },
    { ings: [['mar', 1], ['calamidad', 1]], outputs: ['tormenta', 'tsunami'] },
    { ings: [['tormenta', 1], ['separacion', 1]], outputs: ['viento', 'lluvia'] },
    { ings: [['tormenta', 1], ['luz', 1]], outputs: ['relampago'] },
    { ings: [['criatura-beyonder-acuatica', 1], ['devoracion', 1]], outputs: ['obninsk'] },
    { ings: [['comunidad', 1], ['dominacion', 1]], outputs: ['rey'] },
    { ings: [['trabajo', 1], ['procedimiento', 1]], outputs: ['construccion'] },
    { ings: [['construccion', 1], ['extension', 1]], outputs: ['torre'] },
    { ings: [['humano', 1], ['ritual', 1]], outputs: ['oficiante'] },
    { ings: [['tierra', 1], ['calamidad', 1]], outputs: ['terremoto'] },
    // Cadena de la Corrupción, el Guerrero y la Comunidad
    { ings: [['locura', 1], ['beyonder', 1]], outputs: ['perdida-de-control', 'corrupcion'] },
    { ings: [['corrupcion', 1], ['tiempo', 1]], outputs: ['degeneracion'] },
    { ings: [['humano', 1], ['fuerza', 1]], outputs: ['guerrero'] },
    { ings: [['experiencia-2', 1], ['guerrero', 1]], outputs: ['caballero'] },
    { ings: [['familia', 2]], outputs: ['comunidad'] },
    { ings: [['angel', 1], ['familia', 1]], outputs: ['familia-angelical'] },
    {
      ings: [['familia-angelical', 1], ['arbitro', 1]],
      outputs: ['familia-augustus', 'abogado'],
    },
    {
      ings: [['familia-angelical', 1], ['abogado', 1]],
      outputs: ['familia-augustus', 'arbitro'],
    },
    { ings: [['divinidad', 1], ['comunidad', 1]], outputs: ['religion'] },
    { ings: [['existencia-oculta', 1], ['religion', 1]], outputs: ['organizacion-secreta'] },
    { ings: [['organizacion-secreta', 1], ['seer', 1]], outputs: ['orden-secreta'] },
    {
      ings: [['organizacion-secreta', 1], ['secret-suplicant', 1]],
      outputs: ['orden-aurora'],
    },
    { ings: [['religion', 1], ['ciudad', 1]], outputs: ['iglesia'] },
    { ings: [['nacion', 1], ['familia-augustus', 1]], outputs: ['reino-de-loen'] },
    {
      ings: [['reino-de-loen', 1], ['iglesia', 1]],
      outputs: [
        'iglesia-del-senor-de-las-tormentas',
        'iglesia-de-la-noche-eterna',
        'iglesia-del-dios-del-vapor-y-la-maquinaria',
      ],
    },
    { ings: [['comunidad', 2]], outputs: ['ciudad'] },
  ]
}
